export interface KnowledgeArticle {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  industry?: string;
  service?: string;
  tags: string[];
  author: string;
  date: string;
  readTime: string;
  image?: string;
}

export const knowledgeCategories = [
  { id: "printing-tips", label: "Printing Tips" },
  { id: "signage-guide", label: "Signage Guides" },
  { id: "packaging-design", label: "Packaging Design" },
  { id: "vehicle-branding", label: "Vehicle Branding" },
  { id: "promo-products", label: "Promotional Products" },
  { id: "business-growth", label: "Business Growth" },
  { id: "industry-news", label: "Industry News" },
  { id: "exhibitions", label: "Exhibitions & Trade Fairs" },
];

export const knowledgeArticles: KnowledgeArticle[] = [
  {
    id: "ultimate-guide-business-cards",
    slug: "ultimate-guide-business-cards",
    title: "The Ultimate Guide to Business Cards in 2026",
    excerpt: "Everything you need to know about paper, finish, design and printing for business cards that make a lasting impression.",
    content: "Business cards remain the most powerful networking tool...",
    category: "printing-tips",
    tags: ["business cards", "printing", "branding"],
    author: "Packard Promo",
    date: "2026-05-15",
    readTime: "8 min",
  },
  {
    id: "vehicle-branding-roi",
    slug: "vehicle-branding-roi",
    title: "Vehicle Branding ROI: Why Your Fleet is a Marketing Goldmine",
    excerpt: "A single branded vehicle generates 30,000-70,000 daily impressions. Here's how to maximize your fleet's marketing impact.",
    content: "Mobile advertising is one of the highest-ROI marketing channels...",
    category: "vehicle-branding",
    tags: ["vehicle branding", "marketing", "ROI"],
    author: "Packard Promo",
    date: "2026-05-10",
    readTime: "6 min",
  },
  {
    id: "signage-permits-tanzania",
    slug: "signage-permits-tanzania",
    title: "Signage Permits in Tanzania: The Complete 2026 Guide",
    excerpt: "Municipal regulations for shop signs, billboards and outdoor advertising. What you need to know before installing.",
    content: "Installing signage in Tanzania requires permits from local councils...",
    category: "signage-guide",
    tags: ["signage", "permits", "regulations"],
    author: "Packard Promo",
    date: "2026-05-05",
    readTime: "10 min",
  },
  {
    id: "offset-vs-digital",
    slug: "offset-vs-digital-printing",
    title: "Offset vs Digital Printing: When to Use Each",
    excerpt: "Both are essential — but choosing the wrong one wastes money. Here's how to decide based on quantity, quality and budget.",
    content: "The offset vs digital decision depends on three factors...",
    category: "printing-tips",
    tags: ["printing", "offset", "digital"],
    author: "Packard Promo",
    date: "2026-04-28",
    readTime: "7 min",
  },
  {
    id: "promo-products-events",
    slug: "promo-products-for-events",
    title: "Promotional Products That Actually Get Used",
    excerpt: "T-shirts, caps, mugs, bottles, USBs — the best event merch is the kind people actually keep. Here's what works in 2026.",
    content: "Not all promotional products are created equal...",
    category: "promo-products",
    tags: ["promotional products", "events", "marketing"],
    author: "Packard Promo",
    date: "2026-04-20",
    readTime: "9 min",
  },
  {
    id: "packaging-design-east-africa",
    slug: "packaging-design-east-africa",
    title: "Packaging Design Trends That Sell in East Africa",
    excerpt: "Local consumer behavior, retail trends and cultural preferences that drive packaging design success in Tanzania and Kenya.",
    content: "East African consumers respond to specific packaging cues...",
    category: "packaging-design",
    tags: ["packaging", "design", "FMCG"],
    author: "Packard Promo",
    date: "2026-04-12",
    readTime: "8 min",
  },
  {
    id: "shop-signage-essentials",
    slug: "shop-signage-essentials",
    title: "7 Shop Signage Essentials Every Business Needs",
    excerpt: "From illuminated boards to window graphics — the signage that drives foot traffic and brand recall.",
    content: "Your shop sign is your most important advertising asset...",
    category: "signage-guide",
    tags: ["signage", "retail", "shop signs"],
    author: "Packard Promo",
    date: "2026-04-05",
    readTime: "6 min",
  },
  {
    id: "print-design-files",
    slug: "how-to-prep-print-files",
    title: "How to Prepare Print-Ready Files (and Avoid Re-Print Costs)",
    excerpt: "CMYK vs RGB, bleeds, safe zones, file formats — the technical checklist that saves money.",
    content: "Most re-prints happen because of file preparation errors...",
    category: "printing-tips",
    tags: ["design", "print files", "CMYK"],
    author: "Packard Promo",
    date: "2026-03-28",
    readTime: "7 min",
  },
  {
    id: "fleet-branding-guide",
    slug: "fleet-branding-guide",
    title: "Fleet Branding: From Design to Rollout",
    excerpt: "How to plan and execute a multi-vehicle branding project across 10+ vehicles without disrupting operations.",
    content: "Fleet branding is a multi-step project that requires careful planning...",
    category: "vehicle-branding",
    tags: ["fleet", "branding", "rollout"],
    author: "Packard Promo",
    date: "2026-03-22",
    readTime: "8 min",
  },
  {
    id: "corporate-gifts-that-work",
    slug: "corporate-gifts-that-work",
    title: "Corporate Gifts That Actually Get Used (and Remembered)",
    excerpt: "Premium gift sets, executive pens, leather accessories — the corporate gifts that drive real ROI.",
    content: "A good corporate gift is one that's used daily...",
    category: "promo-products",
    tags: ["corporate gifts", "premium", "B2B"],
    author: "Packard Promo",
    date: "2026-03-15",
    readTime: "5 min",
  },
  {
    id: "packaging-food-grade",
    slug: "packaging-food-grade-tanzania",
    title: "Food-Grade Packaging in Tanzania: TBS Compliance Guide",
    excerpt: "TBS food safety standards, food-grade inks, and how to choose compliant packaging for your food business.",
    content: "Tanzania's TBS has specific requirements for food-contact packaging...",
    category: "packaging-design",
    tags: ["food packaging", "TBS", "compliance"],
    author: "Packard Promo",
    date: "2026-03-08",
    readTime: "9 min",
  },
  {
    id: "exhibition-stand-roi",
    slug: "exhibition-stand-roi",
    title: "How to Maximize ROI from Your Exhibition Stand",
    excerpt: "Pre-event promotion, on-stand engagement, and post-event follow-up — the playbook for trade show success.",
    content: "An exhibition stand is a significant investment...",
    category: "business-growth",
    tags: ["events", "exhibitions", "B2B"],
    author: "Packard Promo",
    date: "2026-03-01",
    readTime: "7 min",
  },
  {
    id: "sabasaba-exhibition-guide",
    slug: "sabasaba-exhibition-guide",
    title: "How to Prepare for Sabasaba Exhibition: The Complete Guide",
    excerpt: "A step-by-step guide to preparing for the Dar es Salaam International Trade Fair. Exhibition stand booking, branding checklist, promotional products, and tips for a successful Sabasaba experience.",
    content: "Sabasaba — the Dar es Salaam International Trade Fair — is Tanzania's largest annual business exhibition, drawing thousands of exhibitors and visitors to the Mwalimu J.K. Nyerere Grounds every July. Preparing effectively for Sabasaba can be the difference between a productive exhibition and a missed opportunity. This guide covers everything from booth booking and stand design to promotional merchandise and post-event follow-up. Start planning 4-6 weeks ahead. Book your exhibition space through TANTRADE, then engage an exhibition stand designer to create a booth that reflects your brand. Order PVC banners, roll-up displays, teardrop flags, and backdrop banners from a trusted large format printer in Dar es Salaam. Print brochures, flyers, and business cards for visitor handouts. Source promotional products like branded T-shirts, caps, corporate gifts, and giveaways that keep your brand in front of prospects long after the fair ends. Plan your on-stand activities — product demos, competitions, and lead capture — and train your booth staff on engagement techniques. After Sabasaba, follow up with leads within 48 hours while your brand is still fresh in their minds. Packard Promo provides end-to-end Sabasaba exhibition branding services in Dar es Salaam, from stand design to promotional merchandise delivery.",
    category: "business-growth",
    tags: ["sabasaba", "exhibitions", "trade fair", "Dar es Salaam"],
    author: "Packard Promo",
    date: "2026-06-01",
    readTime: "8 min",
  },
  {
    id: "exhibition-stand-design-guide",
    slug: "exhibition-stand-design-guide",
    title: "Exhibition Stand Design Guide Tanzania: Stand Out at Sabasaba",
    excerpt: "How to design an exhibition stand that attracts visitors and communicates your brand. Modular vs custom stands, 3D rendering, materials, and budgeting for Tanzanian trade fairs.",
    content: "Your exhibition stand is the centrepiece of your trade fair presence. At events like Sabasaba in Dar es Salaam, where hundreds of exhibitors compete for attention, a well-designed stand can dramatically increase foot traffic and lead generation. This guide covers the key considerations for exhibition stand design in Tanzania. First, understand your space — a standard 3x3m shell scheme requires a different approach than a custom 6x3m corner stand or a 100sqm island booth. Modular aluminium extrusion systems offer flexibility and reusability. Custom wood and steel fabrication creates a premium, branded environment. Tension fabric stands provide lightweight, portable options with full-colour graphic printing. Your stand should incorporate clear branding, product display areas, a meeting space, and storage. Lighting, flooring, and graphics all contribute to the overall impression. Work with an experienced exhibition stand builder in Tanzania who can produce 3D renders for client approval before fabrication. Set a realistic budget that includes design, fabrication, graphics, transport, installation, and breakdown. Packard Promo designs and builds exhibition stands for Sabasaba and other major trade fairs across Tanzania.",
    category: "business-growth",
    tags: ["exhibition stands", "stand design", "trade fair", "Sabasaba"],
    author: "Packard Promo",
    date: "2026-06-03",
    readTime: "7 min",
  },
  {
    id: "best-promotional-products-trade-shows",
    slug: "best-promotional-products-trade-shows",
    title: "Best Promotional Products for Trade Shows in Tanzania",
    excerpt: "The most effective promotional products for Sabasaba and other Tanzanian exhibitions. T-shirts, caps, corporate gifts, branded merchandise that visitors actually keep and use.",
    content: "Promotional products are a proven way to attract visitors to your exhibition stand and keep your brand top-of-mind after the event. At Sabasaba and other trade fairs across Tanzania, choosing the right giveaways can significantly boost your lead generation and brand recall. The best promotional products for exhibitions are useful, high-quality, and visibly branded. Custom T-shirts are perennial favourites — visitors wear them, giving you mobile advertising long after the exhibition. Branded caps provide similar visibility. Corporate gifts like power banks, USB drives, water bottles, and vacuum flasks are practical items recipients use daily, creating repeated brand impressions. Pens, notepads, and diaries are low-cost options for high-volume distribution. For premium leads, executive gift sets containing branded leather accessories, luxury pens, or desk organisers convey quality and professionalism. When selecting promotional products for Sabasaba, consider the Dar es Salaam climate — water bottles, caps, and fans are always appreciated. Order 4-6 weeks before the event to allow for production and shipping. Packard Promo sources and customises promotional products for Sabasaba exhibitors, offering screen printing, embroidery, sublimation, and laser engraving with consistent brand reproduction.",
    category: "promo-products",
    tags: ["promotional products", "trade shows", "corporate gifts", "Sabasaba"],
    author: "Packard Promo",
    date: "2026-06-05",
    readTime: "6 min",
  },
  {
    id: "sabasaba-branding-checklist",
    slug: "sabasaba-branding-checklist",
    title: "Sabasaba Branding Checklist: Complete Exhibition Preparation",
    excerpt: "A comprehensive branding checklist for the Dar es Salaam International Trade Fair. From exhibition stands to promotional products, ensure nothing is missed for your Sabasaba presence.",
    content: "Preparing for Sabasaba requires coordinating multiple branding elements across different suppliers. Use this checklist to ensure every aspect of your exhibition presence is covered. Booth Structure: exhibition stand (modular or custom), pop-up display, promotional table, registration counter, branded backdrop. Signage: PVC banners (outdoor), roll-up banners (indoor), teardrop flags (entrance), booth number sign, directional signage. Printed Materials: brochures, flyers, business cards, product catalogues, company profiles, conference folders, notepads. Promotional Products: T-shirts, caps, corporate gifts, branded mugs, pens, power banks, water bottles, bags. Apparel: staff uniforms or branded attire for booth staff. Digital: presentation screens, digital catalogues, QR code displays, social media content for live posting. Stationery: branded folders for proposals, order forms, lead capture forms. Each item should be designed with consistent branding — colours, fonts, and logo placement. Start planning 6 weeks before Sabasaba. Order exhibition stands and custom items first (4-6 weeks lead time). Printed materials need 1-2 weeks. Promotional products need 2-3 weeks. Allow 1 week for delivery and quality checks before the exhibition. Packard Promo can supply all Sabasaba branding needs from a single source, ensuring consistency across every element.",
    category: "business-growth",
    tags: ["sabasaba", "branding checklist", "exhibition", "trade fair"],
    author: "Packard Promo",
    date: "2026-06-07",
    readTime: "5 min",
  },
  {
    id: "exhibition-banner-sizes-guide",
    slug: "exhibition-banner-sizes-guide",
    title: "Exhibition Banner Sizes Guide: Sabasaba & Trade Fair Standards",
    excerpt: "Standard banner sizes for exhibitions in Tanzania. PVC banners, roll-up banners, teardrop flags, backdrops — dimensions, materials, and placement tips for Sabasaba and other trade fairs.",
    content: "Choosing the right banner sizes for your exhibition can be confusing. This guide covers standard dimensions for every type of trade fair banner in Tanzania, with recommendations for Sabasaba at the Mwalimu J.K. Nyerere Grounds in Dar es Salaam. PVC Banners: Standard sizes include 3x2ft (small signage), 4x3ft (medium), 8x4ft (large), and custom sizes up to 16x8ft for hero placements. Use 440gsm+ PVC with reinforced edges and eyelets for outdoor durability. Roll-Up Banners: Most common are 850x2000mm (standalone), 1000x2200mm (wide format), and 1200x2300mm (premium). Retractable stands are portable and professional for indoor booth areas. Teardrop Banners: Sizes include 3m (sail), 4m (mast), and 5m (oversized) heights. Feather flags with screen-printed or dye-sublimated graphics are effective for outdoor attraction. Backdrop Banners: Step-and-repeat backdrops typically measure 8x8ft or 10x8ft. Fabric tension backdrops offer wrinkle-free premium appearance in sizes from 3x2m to 6x3m. Pop-Up Displays: Standard backwall sizes are 10x10ft, 10x8ft, and 8x8ft with aluminium frames and graphic panels. For Sabasaba, order a mix of outdoor PVC banners for external visibility, roll-up banners for booth interior, and teardrop flags to draw foot traffic from a distance. Packard Promo prints exhibition banners in all standard and custom sizes with fast turnaround in Dar es Salaam.",
    category: "signage-guide",
    tags: ["banner sizes", "exhibition banners", "trade fair", "Sabasaba"],
    author: "Packard Promo",
    date: "2026-06-09",
    readTime: "6 min",
  },
  {
    id: "delivery-times-tanzania",
    slug: "delivery-times-tanzania",
    title: "Printing Delivery Times Across Tanzania: City-by-City Guide",
    excerpt: "How long does printing take in each Tanzanian city? Same-day Dar es Salaam, next-day Zanzibar and Arusha, 2-3 days to Mwanza, Mbeya, Dodoma. Complete delivery timeline for every product.",
    content: "Understanding delivery times is critical for planning any printing, signage, packaging or promotional products order in Tanzania. Packard Promo operates from a 12,000 sqm production facility in Dar es Salaam and delivers nationwide. Here are the city-by-city delivery timelines: Dar es Salaam — same-day printing and delivery for business cards, flyers, posters and most stationery products when artwork is ready before noon. Signage installation within 3-5 business days. Vehicle branding 2-4 business days. Zanzibar — next-day delivery for standard printed materials. Signage and packaging 3-5 business days. Resort and hospitality projects scheduled with 2-week lead time. Arusha — next-day to 2-day delivery for stationery and promotional products. Signage projects 5-10 business days including installation. Mwanza — 2-3 day delivery for printed materials. Large signage and fleet branding 5-10 business days. Dodoma — 2-day delivery for stationery. Government and institutional projects quoted with specific timelines. Mbeya — 2-3 day delivery for standard products. Industrial signage and packaging 7-14 business days. Morogoro — 1-2 day delivery for stationery. Large format and signage 5-7 business days. Tanga — 2-3 day delivery. Heavy-duty signage and export packaging quoted individually. Factors affecting delivery: artwork readiness (provide print-ready PDF files), quantity (large runs need more production time), finish complexity (lamination, foil, spot UV add 1-2 days), and installation requirements (signage needs site survey first). For rush orders, contact Packard Promo on WhatsApp at +255 716 002 790 for expedited production and delivery across Tanzania.",
    category: "printing-tips",
    tags: ["delivery", "Tanzania", "logistics", "turnaround"],
    author: "Packard Promo",
    date: "2026-06-15",
    readTime: "5 min",
  },
  {
    id: "digital-vs-offset-deep-dive",
    slug: "digital-vs-offset-deep-dive",
    title: "Digital vs Offset Printing in Tanzania: Complete Decision Guide",
    excerpt: "Which printing method saves you money? Digital for short runs, offset for volume — but the crossover point depends on your product. Full comparison with Tanzania-specific pricing.",
    content: "Choosing between digital and offset printing in Tanzania depends on quantity, quality requirements, turnaround time, and budget. Here is a complete decision guide with Tanzania-specific pricing from Packard Promo. Digital Printing uses HP Indigo and Konica Minolta presses. Best for: quantities under 1,000 units, fast turnaround (same-day to 48 hours), variable data printing (personalized names, numbers), short-run packaging prototypes, and proofing. Business cards: TZS 18,000 for 100 pieces (TZS 180/each). Flyers: TZS 25,000 for 100 A4 flyers (TZS 250/each). Posters: TZS 8,000 for 10 A3 posters (TZS 800/each). Digital excels at low quantities with no setup fees. Offset Printing uses Heidelberg Speedmaster presses. Best for: quantities above 1,000 units, color-critical work requiring Pantone matching, large format runs, books, magazines, and bulk brochures. The break-even point is typically 500-2,000 units depending on the product. Brochures: TZS 220/each at 5,000 units vs TZS 750/each at 50 units digitally. Books: TZS 350/each at 1,000 units vs TZS 4,500/each at 200 units digitally. NCR Receipt Books: TZS 180/book at 1,000 units — far cheaper than digital at volume. Key differences: Setup cost — digital has zero setup, offset has plate-making fees amortized across the run. Per-unit cost — offset becomes cheaper above the break-even quantity. Color accuracy — offset with Pantone spot colors is more consistent across large runs. Turnaround — digital is 4x faster for short runs. Paper options — offset handles a wider range of paper weights and types. For businesses in Tanzania, the recommendation is: use digital for urgent orders, small batches, and prototypes. Use offset for bulk orders, regular reprints, and color-critical work. Many clients use both — digital for initial runs and proofs, offset for production volumes. Packard Promo offers both digital and offset printing from the same facility, allowing seamless transitions between methods as your quantity needs grow.",
    category: "printing-tips",
    tags: ["digital printing", "offset printing", "comparison", "pricing"],
    author: "Packard Promo",
    date: "2026-06-12",
    readTime: "7 min",
  },
];

export function getArticleBySlug(slug: string): KnowledgeArticle | undefined {
  return knowledgeArticles.find((a) => a.slug === slug);
}
