import type { PortfolioProject } from "@/types";

export interface CaseStudyNarrative {
  challenge: string;
  solution: string;
  deliverables: string[];
  outcome: string;
  metrics: { label: string; value: string }[];
  testimonial?: { quote: string; author: string; role: string };
}

export interface PortfolioProjectExtended extends PortfolioProject {
  challenge?: string;
  solution?: string;
  deliverables?: string[];
  outcome?: string;
  metrics?: { label: string; value: string }[];
  testimonial?: { quote: string; author: string; role: string };
  duration?: string;
  teamSize?: string;
  images?: string[];
}

export const portfolioCategories = [
  { id: "printing", label: "Printing", icon: "M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0" },
  { id: "packaging", label: "Packaging", icon: "M21 7.5l-2.25-1.313M21 7.5v2.25m0-2.25-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313" },
  { id: "signage", label: "Signage", icon: "M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09" },
  { id: "vehicle-branding", label: "Vehicle Branding", icon: "M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0" },
  { id: "promotional-products", label: "Promotional Products", icon: "M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25" },
  { id: "exhibition-displays", label: "Exhibition Displays", icon: "M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5" },
];

export const portfolioProjects: PortfolioProject[] = [
  {
    id: "crdb-branch-signage",
    slug: "crdb-branch-signage",
    title: "CRDB Bank — 12-Branch Signage Rollout",
    client: "CRDB Bank PLC",
    category: "Signage",
    industry: "Banking",
    description: "Manufacture and installation of illuminated signboards for 12 new branch locations across Dar es Salaam, Dodoma, Arusha, Mwanza, Mbeya and Zanzibar. Full project management from site survey to final commissioning.",
    services: ["Site survey", "3D design", "LED illuminated signboards", "Pylon signage", "Installation", "Project management"],
    image: "/images/crdb-banking-branding.jpg",
    gallery: ["/images/crdb-banking-branding.jpg", "/images/crdb-brand-transformation.jpg", "/images/illuminated signage.jpg", "/images/led illuminated sign.jpg", "/images/3d sign.jpg", "/images/reception  wall sign.jpg"],
    year: "2025",
    location: "6 cities nationwide",
    challenge: "CRDB Bank was opening 12 new branches in 6 cities within a 90-day window. Each branch needed a complete signage package — exterior, interior, regulatory and wayfinding — that complied with both CRDB's brand guidelines and local municipal regulations. Coordinating installation across 6 cities with different permitting timelines was a major logistical challenge.",
    solution: "We assembled a dedicated multi-city project team and ran 3 parallel installation crews. Our in-house design team produced sign-off-ready 3D renders within 5 days. We pre-fabricated all signage components in our Dar es Salaam facility and shipped to each city. Local permit teams worked in parallel with production. Each branch received a dedicated project manager and standardized quality checklist.",
    deliverables: ["48 illuminated ACP signboards", "12 illuminated pylon signs", "120 interior wayfinding signs", "60 regulatory signs", "12 reception logo walls", "Project management for 6 cities"],
    outcome: "All 12 branches opened on schedule. The signage system was approved by CRDB's brand committee on first review. The standardized approach reduced per-branch production cost by 18% and is now the template for all future CRDB rollouts.",
    metrics: [
      { label: "Branches delivered", value: "12" },
      { label: "Cities covered", value: "6" },
      { label: "Signage units", value: "240+" },
      { label: "On-time delivery", value: "100%" },
    ],
    testimonial: {
      quote: "Packard Promo handled our 12-branch rollout in record time. The quality of materials and installation precision was on another level.",
      author: "Sarah Mwakasege",
      role: "Brand Manager, CRDB Bank Foundation",
    },
    duration: "90 days",
    teamSize: "Multi-city team of 18 specialists",
  },
  {
    id: "vodacom-vehicle-fleet",
    slug: "vodacom-vehicle-fleet",
    title: "Vodacom Tanzania — 65-Vehicle Fleet Rebrand",
    client: "Vodacom Tanzania",
    category: "Vehicle Branding",
    industry: "Telecommunications",
    description: "Complete rebrand of Vodacom's sales and service fleet — 65 sedans and pickups across Tanzania. Premium 3M vinyl with anti-graffiti laminate.",
    services: ["Fleet audit", "Vinyl design", "Production", "On-site installation", "Quality control"],
    image: "/images/vehicle branding.jpg",
    gallery: ["/images/vehicle branding.jpg", "/images/wheel cover.jpg", "/images/vodacom-billboard.jpg", "/images/outdoor-advertising.jpg"],
    year: "2025",
    location: "Dar es Salaam, Arusha, Mwanza",
    challenge: "Vodacom Tanzania was rebranding its sales and service fleet of 65 vehicles across 3 regions. The challenge: minimize vehicle downtime (each vehicle off-road = lost sales appointments), ensure brand consistency across sedans, pickups and SUVs, and deliver within 21 days.",
    solution: "We deployed 3 mobile installation teams operating simultaneously in Dar, Arusha and Mwanza. Each team had 4 specialists and a mobile vinyl-cutting station. Vehicles were scheduled in batches of 5 per day to maintain service continuity. We used 3M IJ180Cv3 cast vinyl with anti-graffiti laminate for 5-7 year outdoor durability.",
    deliverables: ["65 vehicle wraps (full and partial)", "Premium 3M IJ180Cv3 vinyl", "Anti-graffiti laminate", "Mobile installation teams (3 cities)", "Quality control protocol"],
    outcome: "All 65 vehicles rebranded in 19 days (2 days ahead of schedule). Zero days of sales disruption — vehicles were taken out of service for less than 4 hours each. The fleet's mobile ad-impression value is estimated at 4.2 million daily impressions across Tanzania.",
    metrics: [
      { label: "Vehicles branded", value: "65" },
      { label: "Days to complete", value: "19" },
      { label: "Daily impressions", value: "4.2M" },
      { label: "Vinyl warranty", value: "5-7 yrs" },
    ],
    duration: "21 days",
    teamSize: "12 specialists across 3 cities",
  },
  {
    id: "azam-50k-notebooks",
    slug: "azam-50k-notebooks",
    title: "Azam Media — 50,000 Branded Notebooks",
    client: "Azam Media",
    category: "Printing",
    industry: "Media",
    description: "Offset printing of 50,000 branded A5 notebooks for Azam's nationwide customer loyalty campaign. Delivered in 3 batches over 6 weeks.",
    services: ["Print production", "UV color printing", "PUR binding", "Foil stamped logo", "Variable batch numbering"],
    image: "/images/note book.jpg",
    gallery: ["/images/note book.jpg", "/images/offset printing.jpg", "/images/printing-stationery-scene.jpg", "/images/letter head.jpg", "/images/corporate-portfolio-showcase.jpg"],
    year: "2025",
    location: "Dar es Salaam (national distribution)",
    challenge: "Azam Media needed 50,000 branded A5 notebooks for a nationwide customer loyalty campaign within 6 weeks. The challenge: maintaining color consistency across 3 production batches, ensuring the notebooks would withstand daily use for 12+ months, and delivering in 3 staggered shipments to 8 regional distribution centers.",
    solution: "We ran 3 Heidelberg offset press batches with 17,000 + 17,000 + 16,000 split, with shared Pantone color matching across all batches. Foil-stamped logo on the cover for premium finish. PUR binding for durability. Each batch went through a 3-stage quality check. We coordinated with Azam's logistics team for regional drop-shipping.",
    deliverables: ["50,000 PUR-bound A5 notebooks", "Foil-stamped cover logo", "Variable batch numbering", "Pantone color matching across 3 batches", "Regional drop-shipping to 8 cities"],
    outcome: "Delivered 2 days ahead of schedule. Color consistency was 99.7% across all 3 batches (measured with spectrophotometer). Zero returns or quality complaints. The notebooks became Azam's signature customer gift and the campaign exceeded redemption targets by 22%.",
    metrics: [
      { label: "Units delivered", value: "50,000" },
      { label: "Production batches", value: "3" },
      { label: "Color match", value: "99.7%" },
      { label: "Returns", value: "0" },
    ],
    duration: "6 weeks (3 batches)",
    teamSize: "8 production specialists",
  },
  {
    id: "serena-resort-packaging",
    slug: "serena-resort-packaging",
    title: "Serena Hotels — Luxury Guest Packaging",
    client: "Serena Hotels",
    category: "Packaging",
    industry: "Hospitality",
    description: "Premium rigid gift boxes and packaging for Serena's VIP guest welcome amenities across 8 resort properties.",
    services: ["Structural design", "Material sourcing", "Foil stamping", "Magnetic closure boxes", "Custom foam inserts"],
    image: "/images/serena-hotel-branding.jpg",
    gallery: ["/images/serena-hotel-branding.jpg", "/images/luxury-hotel-branding.jpg", "/images/packaging.jpg", "/images/product package.jpg", "/images/certificate holder.jpg"],
    year: "2025",
    location: "8 resort properties",
    challenge: "Serena Hotels wanted to elevate their VIP guest welcome experience across 8 resort properties with premium packaging. Requirements: luxury rigid boxes with magnetic closure, custom foam inserts for amenities, foil-stamped logos, and consistent design across all properties — but adaptable to each property's unique identity.",
    solution: "Our packaging studio designed a modular rigid box system that allowed each resort to customize the cover wrap while maintaining a consistent structural format. We used pearl-textured wrap paper, gold foil stamping, and custom-cut foam inserts for each property's amenity set. Production was staggered to deliver 1,000 boxes per property over 4 months.",
    deliverables: ["8,000 rigid magnetic-closure boxes", "Custom foam inserts (8 variants)", "Pearl-textured wrap with foil stamping", "Modular design system for property customization", "4-month staggered production"],
    outcome: "Guest satisfaction scores for welcome amenities increased 34%. The packaging was featured in 3 international hospitality design publications. Serena adopted the system as their global standard for VIP welcome packaging.",
    metrics: [
      { label: "Properties", value: "8" },
      { label: "Boxes delivered", value: "8,000" },
      { label: "Satisfaction lift", value: "+34%" },
      { label: "Design awards", value: "3" },
    ],
    duration: "4 months (staggered)",
    teamSize: "6 packaging specialists",
  },
  {
    id: "dangote-truck-fleet",
    slug: "dangote-truck-fleet",
    title: "Dangote Cement — 48-Truck Fleet Branding",
    client: "Dangote Cement Tanzania",
    category: "Vehicle Branding",
    industry: "Manufacturing",
    description: "Branding of 48 heavy-duty cement trucks with high-durability vinyl designed for highway speeds and 18+ month outdoor life.",
    services: ["Vinyl production", "Heavy-duty laminate", "On-site installation", "Quality control", "Maintenance program"],
    image: "/images/bakhresa-industrial-branding.jpg",
    gallery: ["/images/bakhresa-industrial-branding.jpg", "/images/vehicle branding.jpg", "/images/manufacturing-industry.jpg", "/images/wheel cover.jpg"],
    year: "2025",
    location: "Mtwara, Dar es Salaam",
    challenge: "Dangote Cement needed 48 heavy-duty cement trucks branded for highway operation. The challenge: vinyl had to withstand 18+ months of highway speeds, dust, sun, and frequent washing — and the trucks couldn't all be off the road at once.",
    solution: "We used heavy-duty cast vinyl with anti-stone-chip laminate, plus reinforced edge sealing on all door cut-outs. Trucks were scheduled in groups of 4 per day to maintain delivery capacity. We deployed a 6-person mobile team to the Dangote depot in Mtwara for 2 weeks. Each truck received a 4-step quality inspection before being released.",
    deliverables: ["48 heavy-duty truck wraps", "3M IJ180Cv3 cast vinyl", "Anti-stone-chip laminate", "Reinforced edge sealing", "6-person mobile installation team", "2-week on-site deployment"],
    outcome: "After 18 months on the road, the wraps still look fresh. Vinyl shows no significant fading, peeling, or damage. Dangote has since engaged us for an additional 36-truck rollout.",
    metrics: [
      { label: "Trucks branded", value: "48" },
      { label: "On-time delivery", value: "100%" },
      { label: "Durability (months)", value: "18+" },
      { label: "Quality issues", value: "0" },
    ],
    duration: "2 weeks on-site",
    teamSize: "6 mobile specialists",
  },
  {
    id: "safaricom-exhibition",
    slug: "safaricom-exhibition",
    title: "Safaricom PLC — SABSA Summit 2025",
    client: "Safaricom PLC",
    category: "Exhibition Displays",
    industry: "Telecommunications",
    description: "Design, fabrication and installation of 100 sqm custom exhibition stand for the East Africa telecoms summit. Featured LED video wall, product demo pods and VIP meeting room.",
    services: ["3D design", "Custom fabrication", "LED video wall", "Furniture", "On-site installation", "Storage & re-use"],
    image: "/images/exhibition stand.jpg",
    gallery: ["/images/exhibition stand.jpg", "/images/backdrop banner.jpg", "/images/x-banner.jpg", "/images/teardrop banner.jpg", "/images/promotional table.jpg"],
    year: "2025",
    location: "Julius Nyerere ICC, Dar es Salaam",
    challenge: "Safaricom needed a 100 sqm custom exhibition stand for the East Africa telecoms summit at the Julius Nyerere ICC. The stand needed: an LED video wall, 3 product demo pods, a VIP meeting room, full backwall branding, and reusability for future events. The build window was just 3 days before the summit opened.",
    solution: "We designed a modular aluminum-frame system that could be reconfigured for future events. Custom joinery for the LED wall and demo pods. Pre-fabrication in our workshop reduced on-site assembly time. Our 8-person installation team worked overnight shifts to meet the 3-day deadline. The system was designed for easy storage and re-use.",
    deliverables: ["100 sqm custom exhibition stand", "LED video wall (3×2m)", "3 product demo pods", "VIP meeting room with branded interior", "Modular aluminum frame", "Re-usable for 5+ future events"],
    outcome: "Stand was completed 6 hours before doors opened. Generated 240+ qualified leads for Safaricom. The modular system has been re-used at 4 subsequent events, delivering a 3.8x ROI on the initial build investment.",
    metrics: [
      { label: "Stand area", value: "100 sqm" },
      { label: "Setup time", value: "72 hrs" },
      { label: "Leads generated", value: "240+" },
      { label: "ROI on build", value: "3.8x" },
    ],
    duration: "3 days on-site",
    teamSize: "8 specialists",
  },
  {
    id: "unicef-campaign",
    slug: "unicef-campaign",
    title: "UNICEF — Back-to-School Campaign Materials",
    client: "UNICEF Tanzania",
    category: "Promotional Products",
    industry: "NGO",
    description: "Complete back-to-school promotional package: 25,000 branded backpacks, 50,000 notebooks, 100,000 pencils, and 500 school banners distributed to 200 schools nationwide.",
    services: ["Product sourcing", "Custom design", "Quality control", "Warehousing", "Nationwide distribution"],
    image: "/images/promo-campaign-tanzania.jpg",
    gallery: ["/images/promo-campaign-tanzania.jpg", "/images/backpack.jpg", "/images/round neck t-shirt.jpg", "/images/cap.jpg", "/images/conference bag.jpg", "/images/featured-projects-cover.jpg"],
    year: "2024",
    location: "200 schools nationwide",
    challenge: "UNICEF Tanzania's annual back-to-school campaign required 25,000 branded backpacks, 50,000 notebooks, 100,000 pencils, and 500 school banners distributed to 200 schools across all regions of Tanzania. The campaign had to launch on a fixed date (school opening) with zero tolerance for delays.",
    solution: "We set up a 90-day production plan with 6-week manufacturing and 4-week distribution. We sourced and quality-controlled all materials in our warehouse. 3 distribution hubs in Dar, Arusha and Mwanza coordinated regional distribution to schools. Our logistics team used real-time tracking to confirm every school received its full kit.",
    deliverables: ["25,000 branded backpacks", "50,000 branded notebooks", "100,000 branded pencils", "500 school banners", "Quality control at receiving", "Real-time distribution tracking"],
    outcome: "All 200 schools received their full kits 5 days before the launch date. The campaign reached 100% of target schools. UNICEF has renewed the partnership for 3 consecutive years.",
    metrics: [
      { label: "Items distributed", value: "175,500" },
      { label: "Schools reached", value: "200" },
      { label: "Distribution hubs", value: "3" },
      { label: "Days early", value: "5" },
    ],
    duration: "90 days",
    teamSize: "15 specialists + logistics",
  },
  {
    id: "university-textbooks",
    slug: "university-textbooks",
    title: "University of Dar es Salaam — 30,000 Textbooks",
    client: "University of Dar es Salaam",
    category: "Printing",
    industry: "Education",
    description: "Bulk offset printing of 30,000 course textbooks across 12 faculties, with custom cover designs and section-sewn bindings.",
    services: ["Bulk offset printing", "Section-sewn binding", "Custom covers", "Sequential numbering", "Delivery to campus"],
    image: "/images/education-sector.jpg",
    gallery: ["/images/education-sector.jpg", "/images/offset printing.jpg", "/images/printing-stationery-scene.jpg", "/images/note book.jpg", "/images/executive diary.jpg"],
    year: "2024",
    location: "Dar es Salaam",
    challenge: "The University of Dar es Salaam needed 30,000 textbooks across 12 faculties, each with custom cover designs, section-sewn bindings (for durability), and sequential numbering for inventory tracking. Standard turnaround would be 8-10 weeks — they needed them in 6.",
    solution: "We ran 3 Heidelberg offset presses in parallel, each producing 10,000 books. Section-sewn signatures for library-grade durability. Custom covers printed in batches matched by Pantone standards. We dispatched 5 delivery vehicles to the campus over 3 days for the main handover, with overflow stock stored at our facility.",
    deliverables: ["30,000 section-sewn textbooks", "Custom cover designs (12 variants)", "Sequential numbering for inventory", "5-vehicle campus delivery", "Overflow stock storage"],
    outcome: "Delivered 4 days ahead of the start of semester. Zero binding failures in the first 6 months of use (compared to industry average of 2-3% failure rate for perfect-bound books). The university has since standardized on our section-sewn format for all course materials.",
    metrics: [
      { label: "Books delivered", value: "30,000" },
      { label: "Days early", value: "4" },
      { label: "Binding failures", value: "0" },
      { label: "Faculty variants", value: "12" },
    ],
    duration: "6 weeks (parallel production)",
    teamSize: "12 production specialists",
  },
  {
    id: "hyatt-signage-system",
    slug: "hyatt-signage-system",
    title: "Hyatt Regency — Complete Wayfinding System",
    client: "Hyatt Regency Dar es Salaam",
    category: "Signage",
    industry: "Hospitality",
    description: "Complete wayfinding, room identification, regulatory and back-of-house signage for 180-room luxury hotel. Bilingual (English + Swahili) throughout.",
    services: ["Wayfinding strategy", "Bilingual design", "ADA compliance", "Custom fabrication", "Installation"],
    image: "/images/luxury-hotel-branding.jpg",
    gallery: ["/images/luxury-hotel-branding.jpg", "/images/sea-cliff-signage.jpg", "/images/wayfinder sign.jpg", "/images/reception  wall sign.jpg", "/images/3d sign2.jpg"],
    year: "2024",
    location: "Dar es Salaam",
    challenge: "Hyatt Regency needed a complete wayfinding system for their 180-room hotel — exterior, interior, regulatory, and back-of-house. All bilingual (English + Swahili), accessible (ADA-compliant), and consistent with Hyatt's global brand standards while reflecting local Tanzanian character.",
    solution: "Our design team created a custom wayfinding strategy that balanced Hyatt's global identity with Tanzanian design elements (Swahili typography, local color accents). All signs were fabricated in brushed stainless steel and frosted acrylic for a luxury feel. We worked overnight during installation to avoid guest disruption.",
    deliverables: ["180+ wayfinding signs", "Bilingual English + Swahili", "ADA-compliant accessibility", "Brushed stainless + frosted acrylic", "Back-of-house staff navigation", "Floor directories"],
    outcome: "Guest navigation requests at the front desk dropped 78%. TripAdvisor reviews mentioning 'easy to navigate' increased 4x. The system has become a reference project for other Hyatt properties in East Africa.",
    metrics: [
      { label: "Signage units", value: "180+" },
      { label: "Languages", value: "2" },
      { label: "Front desk nav requests", value: "-78%" },
      { label: "TripAdvisor mentions", value: "4x" },
    ],
    duration: "8 weeks",
    teamSize: "10 specialists",
  },
  {
    id: "azam-beverage-packaging",
    slug: "azam-beverage-packaging",
    title: "Azam Beverage — Product Packaging Refresh",
    client: "Azam Beverage Industries",
    category: "Packaging",
    industry: "Beverages",
    description: "Refresh of packaging across 18 SKUs of energy drinks, juices and bottled water. New structural design, food-safe inks and shelf-ready shippers.",
    services: ["Dieline design", "Food-safe printing", "Shelf-ready shippers", "Multi-SKU management", "Production at scale"],
    image: "/images/tbl-beverage-branding.jpg",
    gallery: ["/images/tbl-beverage-branding.jpg", "/images/packaging labels.jpg", "/images/packaging.jpg", "/images/product package.jpg", "/images/corporate-portfolio-showcase.jpg"],
    year: "2024",
    location: "Dar es Salaam (national distribution)",
    challenge: "Azam Beverage was refreshing the packaging across 18 SKUs of energy drinks, juices and bottled water. Requirements: new structural design (shelf-ready), food-safe inks, multi-SKU management, and roll-out across national distribution without disrupting ongoing sales.",
    solution: "Our packaging studio created a unified structural design system adaptable to 18 product variants. We coordinated production with Azam's existing inventory turnover — new packaging rolled out as old stock depleted, no sales disruption. Food-safe inks and FDA/TBS compliant materials throughout. Shelf-ready shippers designed for retail display efficiency.",
    deliverables: ["18 SKU packaging refresh", "Unified structural design system", "Food-safe inks and materials", "Shelf-ready shippers", "Phased roll-out aligned with inventory turnover", "Multi-SKU color management"],
    outcome: "All 18 SKUs rolled out over 6 months. Shelf placement and brand consistency improved measurably. Retailer feedback highlighted the new packaging's shelf impact. Sales velocity increased 14% in the first quarter post-launch.",
    metrics: [
      { label: "SKUs refreshed", value: "18" },
      { label: "Rollout period", value: "6 months" },
      { label: "Sales velocity lift", value: "+14%" },
      { label: "TBS compliance", value: "100%" },
    ],
    duration: "6 months phased rollout",
    teamSize: "8 packaging specialists",
  },
  {
    id: "nmb-corporate-stationery",
    slug: "nmb-corporate-stationery",
    title: "NMB Bank — Corporate Stationery Suite",
    client: "NMB Bank PLC",
    category: "Printing",
    industry: "Banking",
    description: "Full corporate stationery suite across 250 branches: business cards, letterheads, envelopes, branded folders, annual report printing and 2,000+ branded merchandise items.",
    services: ["Stationery design", "Bulk offset printing", "Premium finishes", "Multi-branch logistics", "Inventory management"],
    image: "/images/nmb-bank-evolution.jpg",
    gallery: ["/images/nmb-bank-evolution.jpg", "/images/business card2.jpg", "/images/letter head.jpg", "/images/envelop.jpg", "/images/corporate business card.jpg", "/images/industry-banking-finance-tanzania.jpg"],
    year: "2024",
    location: "250 branches nationwide",
    challenge: "NMB Bank needed a unified corporate stationery suite for 250 branches — business cards, letterheads, envelopes, branded folders, annual report printing, and 2,000+ branded merchandise items. The challenge: ensure every item across 250 branches meets exact brand standards while managing cost and delivery time.",
    solution: "We built a centralized brand asset library with NMB's pre-approved templates, then offered 250-branch self-service ordering through our portal. Bulk offset printing for the highest-volume items (letterheads, envelopes, business cards). Centralized inventory management with quarterly stock replenishment to each region. Annual reports produced in premium quality for board-level distribution.",
    deliverables: ["250-branch stationery standardization", "Centralized brand asset library", "Self-service ordering portal", "Bulk offset printing", "Annual report production", "2,000+ branded merchandise items"],
    outcome: "NMB reduced stationery procurement time by 65%. Per-branch print costs dropped 22% through volume aggregation. Brand consistency reached 99% across all 250 branches. The system now handles all of NMB's stationery needs on autopilot.",
    metrics: [
      { label: "Branches standardized", value: "250" },
      { label: "Procurement time saved", value: "65%" },
      { label: "Cost reduction", value: "22%" },
      { label: "Brand consistency", value: "99%" },
    ],
    duration: "Ongoing (quarterly replenishment)",
    teamSize: "5 dedicated account team",
  },
  {
    id: "airtel-billboard",
    slug: "airtel-billboard",
    title: "Airtel Tanzania — 18-Site Billboard Campaign",
    client: "Airtel Tanzania",
    category: "Signage",
    industry: "Telecommunications",
    description: "Production and installation of 18 large-format billboard campaigns across Dar es Salaam, Arusha, Dodoma, Mwanza and Mbeya. Full campaign management from skinning to photography.",
    services: ["Billboard production", "Site survey", "Installation", "Photography", "Maintenance"],
    image: "/images/outdoor-advertising.jpg",
    gallery: ["/images/outdoor-advertising.jpg", "/images/vodacom-billboard.jpg", "/images/large format printing.jpg", "/images/offset printing.jpg"],
    year: "2024",
    location: "5 cities nationwide",
    challenge: "Airtel Tanzania was launching a new product line and needed immediate outdoor visibility across 5 major cities. Requirements: 18 large-format billboard sites, end-to-end production (printing + installation), photography for campaign tracking, and 21-day turnaround from concept to live.",
    solution: "We pre-negotiated access to 18 strategic billboard sites across 5 cities. Our production team printed all 18 skins in 5 days on our large-format printers. 4 installation teams deployed simultaneously to install all sites in 8 days. Aerial photography captured each site for campaign reporting. Monthly maintenance visits included.",
    deliverables: ["18 billboard sites in 5 cities", "Full production and installation", "Aerial photography per site", "Monthly maintenance", "Strategic site selection", "21-day campaign launch"],
    outcome: "All 18 sites live in 19 days. The campaign reached an estimated 2.8 million impressions in the first month. Airtel renewed for 3 consecutive quarters. The photography set became the standard for Airtel's national outdoor campaigns.",
    metrics: [
      { label: "Billboard sites", value: "18" },
      { label: "Cities", value: "5" },
      { label: "Daily impressions", value: "2.8M" },
      { label: "Days to launch", value: "19" },
    ],
    duration: "21 days (3 weeks)",
    teamSize: "12 specialists across 5 cities",
  },
];

export function getProjectBySlug(slug: string) {
  return portfolioProjects.find((p) => p.slug === slug);
}
