export type ProductCategory =
  | "Business Cards"
  | "Printing Services"
  | "Promotional Products"
  | "Corporate Gifts"
  | "Apparel & Uniforms"
  | "Signage"
  | "Packaging"
  | "Event Branding"
  | "Vehicle Branding"
  | "Office Branding"
  | "Awards & Recognition"
  | "School Products"
  | "Hospitality Products";

export interface CatalogProduct {
  slug: string;
  name: string;
  image: string;
  category: ProductCategory;
  startingPrice?: number;
  minQty?: number;
  badge?: string;
  badgeColor?: string;
  description?: string;
  serviceSlug?: string;
}

export interface CatalogService {
  slug: string;
  title: string;
  image: string;
  category: ProductCategory;
  description: string;
}

export interface CatalogGalleryImage {
  src: string;
  caption: string;
  alt: string;
  category: ProductCategory;
}

export const productCatalog: CatalogProduct[] = [
  {
    slug: "business-cards",
    name: "Business Cards",
    image: "/images/business card2.jpg",
    category: "Business Cards",
    startingPrice: 18000,
    minQty: 100,
    badge: "Top Seller",
    badgeColor: "from-promo-500 to-pink-500",
    description: "Premium 350gsm+ business cards with foil, spot UV, edge painting. Same-day delivery.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "business-cards-deluxe",
    name: "Deluxe Business Cards",
    image: "/images/business card3.jpg",
    category: "Business Cards",
    startingPrice: 25000,
    minQty: 100,
    description: "Deluxe business cards with rounded corners, soft-touch lamination, and metallic foil.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "executive-business-cards",
    name: "Executive Business Cards",
    image: "/images/corporate business card.jpg",
    category: "Business Cards",
    startingPrice: 35000,
    minQty: 100,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "Luxury 600gsm cotton cards, foil stamped, beveled edges. For executives who demand the best.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "business-card-holders",
    name: "Business Card Holders",
    image: "/images/business  card holder.jpg",
    category: "Corporate Gifts",
    startingPrice: 8500,
    minQty: 25,
    description: "Metal, leather and acrylic business card holders with engraved branding.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "t-shirts",
    name: "Branded T-Shirts",
    image: "/images/round neck t-shirt.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 8500,
    minQty: 25,
    badge: "Top Seller",
    badgeColor: "from-promo-500 to-pink-500",
    description: "Custom round neck T-shirts. Screen print, DTF, heat transfer. 180-200gsm cotton.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "uniforms",
    name: "Custom Uniforms",
    image: "/images/uniform.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 22000,
    minQty: 25,
    description: "Full corporate uniform sets: shirts, trousers, overalls. Custom tailoring and embroidery.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "security-uniforms",
    name: "Security Uniforms",
    image: "/images/security uniform.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 28000,
    minQty: 20,
    description: "Professional security guard uniforms. Reflective stripes, epaulettes, branded.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "reflector-jackets",
    name: "Reflector Jackets",
    image: "/images/reflector jacket.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 14500,
    minQty: 25,
    badge: "Trending",
    badgeColor: "from-cyan-500 to-blue-500",
    description: "High-visibility safety jackets with reflective tape. Screen print or embroidery.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "caps",
    name: "Branded Caps",
    image: "/images/cap.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 6500,
    minQty: 25,
    badge: "Trending",
    badgeColor: "from-cyan-500 to-blue-500",
    description: "Baseball, trucker, snapback caps with 3D embroidered logo.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "wheel-covers",
    name: "Wheel Covers",
    image: "/images/wheel cover.jpg",
    category: "Vehicle Branding",
    startingPrice: 12000,
    minQty: 4,
    badge: "Hot",
    badgeColor: "from-rose-500 to-red-500",
    description: "Custom printed car wheel covers for vehicle branding. Full color, weatherproof.",
    serviceSlug: "vehicle-branding",
  },
  {
    slug: "branded-mugs",
    name: "Branded Mugs",
    image: "/images/coffee mug.jpg",
    category: "Promotional Products",
    startingPrice: 4500,
    minQty: 25,
    badge: "Top Seller",
    badgeColor: "from-promo-500 to-pink-500",
    description: "Ceramic mugs, travel mugs, glass mugs. Sublimation and laser engraving.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "branded-pens",
    name: "Branded Pens",
    image: "/images/branded pen.jpg",
    category: "Promotional Products",
    startingPrice: 950,
    minQty: 100,
    badge: "Best Value",
    badgeColor: "from-emerald-500 to-teal-500",
    description: "Metal, plastic, bamboo pens. Pad print or laser engraved.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "executive-pens",
    name: "Executive Pens",
    image: "/images/executive pen.jpg",
    category: "Corporate Gifts",
    startingPrice: 4500,
    minQty: 50,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "Premium metal executive pens. Twist, click, rollerball. Gift-boxed options.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "water-bottles",
    name: "Branded Water Bottles",
    image: "/images/water bottle.jpg",
    category: "Promotional Products",
    startingPrice: 5500,
    minQty: 50,
    description: "Stainless steel, plastic and glass water bottles. Laser engraved or UV print.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "vacuum-flasks",
    name: "Vacuum Flasks",
    image: "/images/vacuum flask.jpg",
    category: "Corporate Gifts",
    startingPrice: 9500,
    minQty: 25,
    description: "Premium insulated vacuum flasks. 500ml-1L. Logo laser engraved.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "key-holders",
    name: "Branded Key Holders",
    image: "/images/keyholder.jpg",
    category: "Promotional Products",
    startingPrice: 1800,
    minQty: 100,
    description: "Metal, leather, acrylic key holders. Laser engraved or printed.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "usb-flash-drives",
    name: "USB Flash Drives",
    image: "/images/usb flash drive.jpg",
    category: "Corporate Gifts",
    startingPrice: 8500,
    minQty: 50,
    description: "Custom USB drives — wood, metal, leather. 4GB-128GB. Pre-loaded options.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "power-banks",
    name: "Branded Power Banks",
    image: "/images/power bank.jpg",
    category: "Corporate Gifts",
    startingPrice: 18000,
    minQty: 25,
    description: "Custom power banks 5000-20000mAh. Logo print or laser engraving.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "wireless-chargers",
    name: "Wireless Chargers",
    image: "/images/wireless charger.jpg",
    category: "Corporate Gifts",
    startingPrice: 14000,
    minQty: 25,
    badge: "Trending",
    badgeColor: "from-cyan-500 to-blue-500",
    description: "Custom wireless charging pads. Branded with your logo. Premium tech gift.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "umbrellas",
    name: "Branded Umbrellas",
    image: "/images/umbrellar.jpg",
    category: "Promotional Products",
    startingPrice: 9500,
    minQty: 25,
    description: "Golf umbrellas, folding umbrellas with logo print. Rain-proof promotional gift.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "shopping-bags",
    name: "Custom Shopping Bags",
    image: "/images/shopping bag.jpg",
    category: "Packaging",
    startingPrice: 2500,
    minQty: 100,
    description: "Paper, non-woven, canvas shopping bags. Full color print with your brand.",
    serviceSlug: "packaging-printing",
  },
  {
    slug: "conference-bags",
    name: "Conference Bags",
    image: "/images/conference bag.jpg",
    category: "Event Branding",
    startingPrice: 12000,
    minQty: 50,
    description: "Branded conference bags — backpack, duffel, tote styles. Perfect for events.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "laptop-bags",
    name: "Branded Laptop Bags",
    image: "/images/laptop bag.jpg",
    category: "Corporate Gifts",
    startingPrice: 18000,
    minQty: 25,
    description: "Executive laptop bags, sleeves, backpacks. Premium materials with logo.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "backpacks",
    name: "Branded Backpacks",
    image: "/images/backpack.jpg",
    category: "Corporate Gifts",
    startingPrice: 14500,
    minQty: 25,
    description: "Custom backpacks for schools, conferences, and corporate gifts.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "conference-folders",
    name: "Conference Folders",
    image: "/images/conference folder.jpg",
    category: "Event Branding",
    startingPrice: 6500,
    minQty: 50,
    description: "Branded conference folders — A4, A5, with notepad and pen holder.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "executive-diaries",
    name: "Executive Diaries",
    image: "/images/executive diary.jpg",
    category: "Corporate Gifts",
    startingPrice: 12500,
    minQty: 50,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "PU leather diaries with debossed logo. Pen loop, ribbon, elastic closure.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "notebooks",
    name: "Branded Notebooks",
    image: "/images/note book.jpg",
    category: "Office Branding",
    startingPrice: 4500,
    minQty: 100,
    description: "Custom notebooks, journals, planners. Spiral, perfect, or PUR bound.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "desktop-calendars",
    name: "Desktop Calendars",
    image: "/images/desktop calendar.jpg",
    category: "Office Branding",
    startingPrice: 8500,
    minQty: 50,
    description: "Custom desktop calendars with branded images. Year-end corporate gifting.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "table-calendars",
    name: "Table Calendars",
    image: "/images/table calendar2.jpg",
    category: "Office Branding",
    startingPrice: 7500,
    minQty: 50,
    description: "Premium table calendars. Spiral bound with custom photography.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "table-organisers",
    name: "Table Organisers",
    image: "/images/table organiser.jpg",
    category: "Office Branding",
    startingPrice: 12500,
    minQty: 25,
    description: "Branded desk organizers. Acrylic, wood, or metal with logo.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "mouse-pads",
    name: "Branded Mouse Pads",
    image: "/images/mouse pad.jpg",
    category: "Office Branding",
    startingPrice: 3500,
    minQty: 100,
    description: "Custom mouse pads with full color print. Gaming or office styles.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "ncr-books",
    name: "NCR Receipt Books",
    image: "/images/ncr book.jpg",
    category: "Printing Services",
    startingPrice: 180,
    minQty: 1000,
    description: "NCR (carbonless) receipt books. 2-part, 3-part, 4-part. Numbered.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "id-cards",
    name: "ID Cards & Badges",
    image: "/images/id card.jpg",
    category: "Office Branding",
    startingPrice: 4500,
    minQty: 50,
    description: "PVC ID cards with photo, name, position. Optional magnetic strip or chip.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "id-cards-premium",
    name: "Premium ID Cards",
    image: "/images/id card2.jpg",
    category: "Office Branding",
    startingPrice: 6500,
    minQty: 50,
    description: "Premium ID cards with metallic finish and security features.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "id-cards-executive",
    name: "Executive ID Cards",
    image: "/images/id card3.jpg",
    category: "Office Branding",
    startingPrice: 8500,
    minQty: 25,
    description: "Executive ID cards with foil stamping and custom design.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "id-cards-lanyard",
    name: "ID Cards with Lanyard",
    image: "/images/id card with lanyard.jpg",
    category: "Office Branding",
    startingPrice: 6500,
    minQty: 50,
    description: "Complete ID card set with branded lanyard and holder.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "staff-ids",
    name: "Staff ID Cards",
    image: "/images/staff id.jpg",
    category: "Office Branding",
    startingPrice: 5500,
    minQty: 50,
    description: "Staff ID badges with photo, department, position, barcode.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "paper-wristbands",
    name: "Paper Wristbands",
    image: "/images/paper wristband.jpg",
    category: "Event Branding",
    startingPrice: 350,
    minQty: 500,
    description: "Custom paper wristbands for events, festivals, conferences. Tyvek or vinyl.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "silicone-wristbands",
    name: "Silicone Wristbands",
    image: "/images/silicone wristbands.jpg",
    category: "Event Branding",
    startingPrice: 650,
    minQty: 500,
    description: "Debossed, embossed, or printed silicone wristbands. Multiple colors.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "awards",
    name: "Custom Awards",
    image: "/images/award.jpg",
    category: "Awards & Recognition",
    startingPrice: 18000,
    minQty: 5,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "Crystal, glass, acrylic awards with engraving. For corporate recognition.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "trophies",
    name: "Custom Trophies",
    image: "/images/trophy.jpg",
    category: "Awards & Recognition",
    startingPrice: 14500,
    minQty: 5,
    description: "Metal, wood, acrylic trophies. Sports, corporate, school events.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "recognition-certificates",
    name: "Recognition Certificates",
    image: "/images/recognition certificate.jpg",
    category: "Awards & Recognition",
    startingPrice: 4500,
    minQty: 50,
    description: "Premium recognition certificates with foil borders and embossed seals.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "certificate-holders",
    name: "Certificate Holders",
    image: "/images/certificate holder.jpg",
    category: "Awards & Recognition",
    startingPrice: 9500,
    minQty: 25,
    description: "Leather and PU certificate holders with gold foil logo.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "pvc-banners",
    name: "PVC Banners",
    image: "/images/large format printing.jpg",
    category: "Signage",
    startingPrice: 12000,
    minQty: 1,
    badge: "Best Value",
    badgeColor: "from-emerald-500 to-teal-500",
    description: "Heavy-duty 440gsm PVC banners, hemmed with eyelets. 1+ MOQ.",
    serviceSlug: "large-format-printing",
  },
  {
    slug: "rollup-banners",
    name: "Roll-up Banners",
    image: "/images/x-banner.jpg",
    category: "Event Branding",
    startingPrice: 55000,
    minQty: 1,
    badge: "Best Value",
    badgeColor: "from-emerald-500 to-teal-500",
    description: "Retractable roll-up banner stands. 85×200cm. Carrying bag included.",
    serviceSlug: "large-format-printing",
  },
  {
    slug: "teardrop-banners",
    name: "Teardrop Banners",
    image: "/images/teardrop banner.jpg",
    category: "Event Branding",
    startingPrice: 65000,
    minQty: 1,
    description: "Teardrop feather flags. Outdoor events, exhibitions, retail.",
    serviceSlug: "large-format-printing",
  },
  {
    slug: "backdrop-banners",
    name: "Backdrop Banners",
    image: "/images/backdrop banner.jpg",
    category: "Event Branding",
    startingPrice: 145000,
    minQty: 1,
    description: "Step-and-repeat backdrops for events, conferences, and exhibitions.",
    serviceSlug: "large-format-printing",
  },
  {
    slug: "shop-signboards",
    name: "Shop Signboards",
    image: "/images/illuminated signage.jpg",
    category: "Signage",
    startingPrice: 180000,
    minQty: 1,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "Illuminated ACP, acrylic, 3D letters. Free site survey.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "led-signs",
    name: "LED Signs & Letters",
    image: "/images/illuminated light box.jpg",
    category: "Signage",
    startingPrice: 85000,
    minQty: 1,
    description: "LED channel letters, halo-lit, front-lit. 5+ year lifespan.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "led-illuminated-signs",
    name: "LED Illuminated Signs",
    image: "/images/led illuminated sign.jpg",
    category: "Signage",
    startingPrice: 95000,
    minQty: 1,
    description: "LED illuminated signs with energy-efficient modules. Indoor and outdoor.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "3d-signs",
    name: "3D Acrylic Signs",
    image: "/images/3d sign.jpg",
    category: "Signage",
    startingPrice: 65000,
    minQty: 1,
    description: "3D acrylic letters and signs. Premium look for office receptions.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "3d-signs-premium",
    name: "Premium 3D Signs",
    image: "/images/3d sign2.jpg",
    category: "Signage",
    startingPrice: 85000,
    minQty: 1,
    description: "Premium 3D fabricated signs. Stainless steel, brass, acrylic combinations.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "outdoor-signage",
    name: "Outdoor Signage",
    image: "/images/outdoor signage.jpg",
    category: "Signage",
    startingPrice: 95000,
    minQty: 1,
    description: "Heavy-duty outdoor signage. Weather-resistant 5+ year durability.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "reception-signs",
    name: "Reception Wall Signs",
    image: "/images/reception  wall sign.jpg",
    category: "Office Branding",
    startingPrice: 125000,
    minQty: 1,
    description: "3D reception wall signs. Logo, mission, vision displays.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "safety-signage",
    name: "Safety Signage",
    image: "/images/safety signage.jpg",
    category: "Signage",
    startingPrice: 8500,
    minQty: 5,
    description: "Industrial safety signs. Hazard, mandatory, warning, prohibition signs.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "wayfinder-signs",
    name: "Wayfinder Signs",
    image: "/images/wayfinder sign.jpg",
    category: "Signage",
    startingPrice: 45000,
    minQty: 10,
    description: "Complete wayfinding systems for hospitals, schools, malls, hotels.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "glass-branding",
    name: "Glass Branding (Frosted)",
    image: "/images/glass branding frost.jpg",
    category: "Office Branding",
    startingPrice: 9500,
    minQty: 5,
    description: "Frosted vinyl for office glass partitions, doors, and windows.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "promotional-tables",
    name: "Promotional Tables",
    image: "/images/promotional table.jpg",
    category: "Event Branding",
    startingPrice: 95000,
    minQty: 1,
    description: "Branded promotional tables for exhibitions, conferences, and roadshows.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "table-talkers",
    name: "Table Talker Displays",
    image: "/images/table talker display.jpg",
    category: "Event Branding",
    startingPrice: 12500,
    minQty: 10,
    description: "Acrylic and cardboard table talkers for restaurants, cafes, events.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "retail-storefront",
    name: "Retail Storefront Branding",
    image: "/images/retail storefront.jpg",
    category: "Signage",
    startingPrice: 250000,
    minQty: 1,
    description: "Complete retail storefront design and installation.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "brochures",
    name: "Brochures",
    image: "/images/brochure.jpg",
    category: "Printing Services",
    startingPrice: 75000,
    minQty: 50,
    description: "Bi-fold, tri-fold, multi-page brochures. Premium finishes available.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "corporate-brochures",
    name: "Corporate Brochures",
    image: "/images/brochure3.jpg",
    category: "Printing Services",
    startingPrice: 95000,
    minQty: 50,
    description: "Premium corporate brochures. Saddle-stitched, perfect-bound options.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "company-profiles",
    name: "Company Profiles",
    image: "/images/company profile.jpg",
    category: "Printing Services",
    startingPrice: 9500,
    minQty: 100,
    description: "Multi-page corporate profile documents. Premium finish options.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "premium-company-profiles",
    name: "Premium Company Profiles",
    image: "/images/company profile2.jpg",
    category: "Printing Services",
    startingPrice: 14500,
    minQty: 100,
    description: "Premium company profiles with hard cover, foil, and section dividers.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "product-catalogues",
    name: "Product Catalogues",
    image: "/images/product catalogue.jpg",
    category: "Printing Services",
    startingPrice: 12500,
    minQty: 100,
    description: "Multi-page product catalogues. Perfect for retail and B2B.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "annual-reports",
    name: "Annual Reports",
    image: "/images/annual report.jpg",
    category: "Printing Services",
    startingPrice: 12000,
    minQty: 100,
    description: "Premium annual reports and financial statements.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "posters",
    name: "Posters",
    image: "/images/poster.jpg",
    category: "Printing Services",
    startingPrice: 8000,
    minQty: 10,
    description: "Vivid full-color posters for promotions and events.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "stickers-labels",
    name: "Stickers & Labels",
    image: "/images/stickers.jpg",
    category: "Printing Services",
    startingPrice: 15000,
    minQty: 100,
    description: "Custom die-cut stickers and product labels. Waterproof vinyl.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "laptop-stickers",
    name: "Laptop Stickers",
    image: "/images/laptop stickers.jpg",
    category: "Printing Services",
    startingPrice: 3500,
    minQty: 100,
    description: "Custom laptop stickers, vinyl decals, die-cut shapes.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "letterheads",
    name: "Letterheads",
    image: "/images/letter head.jpg",
    category: "Office Branding",
    startingPrice: 32000,
    minQty: 500,
    description: "Corporate letterheads with matching envelopes and compliment slips.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "envelopes",
    name: "Branded Envelopes",
    image: "/images/envelop.jpg",
    category: "Office Branding",
    startingPrice: 28000,
    minQty: 500,
    description: "Custom printed envelopes — DL, C5, C4. Window or plain.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "stamps",
    name: "Custom Stamps",
    image: "/images/stamps.jpg",
    category: "Office Branding",
    startingPrice: 12500,
    minQty: 5,
    description: "Self-inking, pre-inked, and traditional stamps. Logo or text.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "document-wallets",
    name: "Document Wallets",
    image: "/images/document wallet.jpg",
    category: "Office Branding",
    startingPrice: 4500,
    minQty: 100,
    description: "Custom document wallets. Folders with branded logo embossing.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "packaging-boxes",
    name: "Packaging Boxes",
    image: "/images/packaging.jpg",
    category: "Packaging",
    startingPrice: 250,
    minQty: 1000,
    description: "Folding cartons, rigid gift boxes, mailer boxes. Custom dielines.",
    serviceSlug: "packaging-printing",
  },
  {
    slug: "product-packaging",
    name: "Product Packaging",
    image: "/images/product package.jpg",
    category: "Packaging",
    startingPrice: 320,
    minQty: 1000,
    description: "Custom retail packaging with full color print and finishing.",
    serviceSlug: "packaging-printing",
  },
  {
    slug: "packaging-labels",
    name: "Packaging Labels",
    image: "/images/packaging labels.jpg",
    category: "Packaging",
    startingPrice: 180,
    minQty: 1000,
    description: "Custom packaging labels. Sheet or roll format. Food-safe options.",
    serviceSlug: "packaging-printing",
  },
  {
    slug: "vehicle-branding",
    name: "Vehicle Branding",
    image: "/images/vehicle branding.jpg",
    category: "Vehicle Branding",
    startingPrice: 350000,
    minQty: 1,
    badge: "Premium",
    badgeColor: "from-gold-500 to-amber-500",
    description: "Full or partial car wraps. 3M vinyl, 5-7 year durability.",
    serviceSlug: "vehicle-branding",
  },
  {
    slug: "signage-installation",
    name: "Signage Installation",
    image: "/images/signage installation.jpg",
    category: "Signage",
    startingPrice: 25000,
    minQty: 1,
    description: "Professional signage installation. Certified teams, all heights.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "exhibition-stands",
    name: "Exhibition Stands",
    image: "/images/exhibition stand.jpg",
    category: "Event Branding",
    startingPrice: 850000,
    minQty: 1,
    description: "Modular and custom exhibition stands. 3x3m to 100+ sqm.",
    serviceSlug: "exhibition-events",
  },
  {
    slug: "screen-printing",
    name: "Screen Printing",
    image: "/images/screen printing.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 4500,
    minQty: 50,
    description: "Multi-color screen printing on T-shirts, caps, bags.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "screen-printing-multi",
    name: "Multi-Color Screen Print",
    image: "/images/screen printing2.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 5500,
    minQty: 50,
    description: "Multi-color screen printing for branded apparel and merchandise.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "embroidery",
    name: "Embroidery Service",
    image: "/images/embroidery service.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 6500,
    minQty: 25,
    description: "Custom embroidery on caps, polos, jackets, bags.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "premium-embroidery",
    name: "Premium Embroidery",
    image: "/images/embroidery2.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 8500,
    minQty: 25,
    description: "Premium embroidery with metallic threads. For luxury apparel.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "dtf-printing",
    name: "DTF Printing",
    image: "/images/dtf printing.jpg",
    category: "Apparel & Uniforms",
    startingPrice: 4500,
    minQty: 25,
    description: "DTF (Direct-to-Film) heat transfer printing. Full color, no setup.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "digital-printing-svc",
    name: "Digital Printing",
    image: "/images/digital printing.jpg",
    category: "Printing Services",
    startingPrice: 25000,
    minQty: 100,
    description: "HP Indigo digital printing. Business cards, flyers, brochures.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "offset-printing-svc",
    name: "Offset Printing",
    image: "/images/offset printing.jpg",
    category: "Printing Services",
    startingPrice: 4500,
    minQty: 1000,
    description: "Heidelberg offset printing. Books, magazines, annual reports.",
    serviceSlug: "offset-printing",
  },
  {
    slug: "large-format-printing-svc",
    name: "Large Format Printing",
    image: "/images/large format printing.jpg",
    category: "Signage",
    startingPrice: 12000,
    minQty: 1,
    description: "Banners, billboards, wall graphics. Up to 5m wide seamless.",
    serviceSlug: "large-format-printing",
  },
  {
    slug: "logo-design",
    name: "Logo Design",
    image: "/images/logo designing.jpg",
    category: "Printing Services",
    startingPrice: 250000,
    minQty: 1,
    description: "Professional logo design with unlimited revisions.",
    serviceSlug: "design-studio",
  },
  {
    slug: "graphics-design",
    name: "Graphics Design",
    image: "/images/graphics design service.jpg",
    category: "Printing Services",
    startingPrice: 95000,
    minQty: 1,
    description: "Graphics design service for print and digital.",
    serviceSlug: "design-studio",
  },
  {
    slug: "school-products",
    name: "School Branding Package",
    image: "/images/ChatGPT Image Jun 4, 2026, 05_57_06 AM.jpg",
    category: "School Products",
    startingPrice: 850000,
    minQty: 1,
    description: "Complete school branding: books, uniforms, signage, banners.",
    serviceSlug: "promotional-products",
  },
  {
    slug: "showcase-image",
    name: "Showcase Image",
    image: "/images/Gemini_Generated_Image_3t03w93t03w93t03 (1).jpg",
    category: "Printing Services",
    startingPrice: 0,
    minQty: 0,
    description: "AI-generated showcase image for visual variety.",
    serviceSlug: "design-studio",
  },
  {
    slug: "signage-installation-team",
    name: "On-Site Signage Teams",
    image: "/images/signage installation team.jpg",
    category: "Signage",
    startingPrice: 45000,
    minQty: 1,
    description: "Professional on-site signage installation teams.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "signage-transformation",
    name: "Signage Transformation",
    image: "/images/signage installation transformation.jpg",
    category: "Signage",
    startingPrice: 180000,
    minQty: 1,
    description: "Before/after signage transformation projects.",
    serviceSlug: "signage-solutions",
  },
  {
    slug: "customer-delivery",
    name: "Nationwide Delivery",
    image: "/images/customer delivery.jpg",
    category: "Printing Services",
    startingPrice: 5000,
    minQty: 1,
    description: "Free delivery in Dar es Salaam. Nationwide shipping.",
    serviceSlug: "digital-printing",
  },
  {
    slug: "customer-success",
    name: "Customer Success Stories",
    image: "/images/customer success showcase.jpg",
    category: "Printing Services",
    startingPrice: 0,
    minQty: 0,
    description: "Real customer success stories from our 4500+ projects.",
    serviceSlug: "digital-printing",
  },
];

export const categoryConfig: { name: ProductCategory; icon: string; color: string; description: string; count: number }[] = [
  { name: "Business Cards", icon: "M16 7H4a2 2 0 00-2 2v6a2 2 0 002 2h12a2 2 0 002-2V9a2 2 0 00-2-2zM4 9h12v6H4V9z", color: "from-blue-500 to-cyan-500", description: "Premium business cards, executive cards, card holders", count: 0 },
  { name: "Printing Services", icon: "M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m0 0a48.159 48.159 0 0110.5 0m-10.5 0V4.875c0-.621.504-1.125 1.125-1.125h8.25c.621 0 1.125.504 1.125 1.125v3.659", color: "from-emerald-500 to-teal-500", description: "Digital, offset, large format — every print you need", count: 0 },
  { name: "Promotional Products", icon: "M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z", color: "from-pink-500 to-rose-500", description: "Pens, mugs, bottles, key holders and more", count: 0 },
  { name: "Corporate Gifts", icon: "M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z", color: "from-amber-500 to-yellow-500", description: "Premium gifts, executive pens, diaries, USBs", count: 0 },
  { name: "Apparel & Uniforms", icon: "M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z", color: "from-indigo-500 to-blue-500", description: "T-shirts, caps, uniforms, jackets", count: 0 },
  { name: "Signage", icon: "M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z", color: "from-orange-500 to-red-500", description: "Shop signs, LED, 3D letters, billboards", count: 0 },
  { name: "Packaging", icon: "M21 7.5l-2.25-1.313M21 7.5v2.25m0-2.25-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3l2.25-1.313M12 12.75l-2.25-1.313M12 12.75V15m0 6.75l2.25-1.313M12 21.75V19.5m0 2.25-2.25-1.313m0-16.875L12 2.25l2.25 1.313M21 14.25v2.25l-2.25 1.313m-13.5 0L3 16.5v-2.25", color: "from-green-500 to-emerald-500", description: "Folding cartons, gift boxes, mailers, labels", count: 0 },
  { name: "Event Branding", icon: "M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 2.064V3.5A2.5 2.5 0 0017.5 6h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2H21", color: "from-rose-500 to-orange-500", description: "Exhibition stands, banners, conference materials", count: 0 },
  { name: "Vehicle Branding", icon: "M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12", color: "from-teal-500 to-cyan-500", description: "Car wraps, fleet branding, wheel covers", count: 0 },
  { name: "Office Branding", icon: "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z", color: "from-slate-500 to-gray-500", description: "ID cards, letterheads, calendars, desk items", count: 0 },
  { name: "Awards & Recognition", icon: "M16.5 18.75h-9m9 0a3 3 0 013 3h-15a3 3 0 013-3m9 0v-4.5A3.75 3.75 0 0016.5 10.5h-9A3.75 3.75 0 003 14.25V18.75m9-12.75h-3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125H12m0-3.75V6.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v1.5c0 .621-.504 1.125-1.125 1.125H16.5", color: "from-yellow-500 to-amber-500", description: "Trophies, awards, recognition certificates", count: 0 },
  { name: "School Products", icon: "M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-17.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.702 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5", color: "from-amber-500 to-orange-500", description: "School branding, books, uniforms, signage", count: 0 },
  { name: "Hospitality Products", icon: "M8.25 21v-4.875c0-.621.504-1.125 1.125-1.125h5.25c.621 0 1.125.504 1.125 1.125V21m0 0h4.5V3.545M12.75 21h7.5V10.75M2.25 21h1.5m18 0h-18M2.25 9l4.5-1.636M18.75 3l-1.5.545m0 6.205l3 1m1.5.5l-1.5-.5M6.75 7.364V3h-3v18m3-13.636l10.5-3.819", color: "from-fuchsia-500 to-pink-500", description: "Hotel signage, packaging, guest amenities", count: 0 },
];

export const galleryImages: CatalogGalleryImage[] = [
  { src: "/images/business card2.jpg", caption: "Business Cards", alt: "Premium business cards with foil stamping", category: "Business Cards" },
  { src: "/images/round neck t-shirt.jpg", caption: "T-Shirts", alt: "Custom branded T-shirts", category: "Apparel & Uniforms" },
  { src: "/images/cap.jpg", caption: "Caps", alt: "Embroidered caps with 3D logo", category: "Apparel & Uniforms" },
  { src: "/images/coffee mug.jpg", caption: "Mugs", alt: "Branded ceramic mugs", category: "Promotional Products" },
  { src: "/images/illuminated signage.jpg", caption: "Illuminated Signs", alt: "LED illuminated signage", category: "Signage" },
  { src: "/images/packaging.jpg", caption: "Packaging", alt: "Custom packaging boxes", category: "Packaging" },
  { src: "/images/vehicle branding.jpg", caption: "Vehicle Branding", alt: "Vehicle wrap branding", category: "Vehicle Branding" },
  { src: "/images/brochure.jpg", caption: "Brochures", alt: "Multi-page brochures", category: "Printing Services" },
  { src: "/images/executive diary.jpg", caption: "Executive Diaries", alt: "PU leather branded diaries", category: "Corporate Gifts" },
  { src: "/images/award.jpg", caption: "Awards", alt: "Custom crystal awards", category: "Awards & Recognition" },
  { src: "/images/x-banner.jpg", caption: "Roll-up Banners", alt: "Retractable roll-up banners", category: "Event Branding" },
  { src: "/images/stickers.jpg", caption: "Stickers", alt: "Custom die-cut stickers", category: "Printing Services" },
  { src: "/images/keyholder.jpg", caption: "Key Holders", alt: "Branded metal key holders", category: "Promotional Products" },
  { src: "/images/water bottle.jpg", caption: "Water Bottles", alt: "Stainless steel water bottles", category: "Promotional Products" },
  { src: "/images/letter head.jpg", caption: "Letterheads", alt: "Corporate letterheads", category: "Office Branding" },
  { src: "/images/3d sign.jpg", caption: "3D Signs", alt: "3D acrylic signs", category: "Signage" },
  { src: "/images/large format printing.jpg", caption: "Large Format", alt: "Large format printing production", category: "Signage" },
  { src: "/images/digital printing.jpg", caption: "Digital Printing", alt: "HP Indigo digital printing", category: "Printing Services" },
  { src: "/images/embroidery service.jpg", caption: "Embroidery", alt: "Custom embroidery service", category: "Apparel & Uniforms" },
  { src: "/images/conference bag.jpg", caption: "Conference Bags", alt: "Branded conference bags", category: "Event Branding" },
];

export const industriesImageMap: Record<string, string> = {
  schools: "/images/ChatGPT Image Jun 4, 2026, 05_57_06 AM.jpg",
  universities: "/images/education-sector.jpg",
  ngos: "/images/promo-campaign-tanzania.jpg",
  government: "/images/government-branding.jpg",
  telecoms: "/images/industry-telecommunications-tanzania.jpg",
  healthcare: "/images/quality inspection scene printing.jpg",
  hotels: "/images/luxury-hotel-branding.jpg",
  construction: "/images/safety signage.jpg",
  banking: "/images/crdb-banking-branding.jpg",
  manufacturing: "/images/manufacturing-industry.jpg",
};

export const additionalProductImages = {
  // From service-*.jpg legacy images
  printing: "/images/printing-stationery-scene.jpg",
  signage: "/images/sea-cliff-signage.jpg",
  packaging: "/images/tbl-beverage-branding.jpg",
  // Heroes
  hero1: "/images/hero-printing-branding.jpg",
  hero2: "/images/hero-east-african.jpg",
  hero3: "/images/hero-tanzania.jpg",
  // Industries
  industry1: "/images/industry-banking-finance-tanzania.jpg",
  industry2: "/images/industry-government-tanzania.jpg",
  industry3: "/images/industry-hospitality-zanzibar.jpg",
  industry4: "/images/industry-real-estate-tanzania.jpg",
  industry5: "/images/industry-telecommunications-tanzania.jpg",
  // Services
  service1: "/images/service-billboard-advertising.jpg",
  service2: "/images/service-corporate-branding.jpg",
  service3: "/images/service-corporate-printing.jpg",
  service4: "/images/service-design-studio.jpg",
  service5: "/images/service-digital-printing.jpg",
  service6: "/images/service-event-branding.jpg",
  service7: "/images/service-exhibition-branding.jpg",
  service8: "/images/service-large-format-printing.jpg",
  service9: "/images/service-offset-printing.jpg",
  service10: "/images/service-packaging-printing.jpg",
  service11: "/images/service-promotional-campaigns.jpg",
  service12: "/images/service-promotional-products.jpg",
  service13: "/images/service-signage-solutions.jpg",
  service14: "/images/service-signage-systems.jpg",
  service15: "/images/service-vehicle-branding.jpg",
  // Other
  about: "/images/about-hero.jpg",
  featured: "/images/featured-projects-cover.jpg",
  thought: "/images/thought-leadership.jpg",
  marketing: "/images/marketing-strategy-concept.jpg",
  media: "/images/media-intelligence-concept.jpg",
  hospitality: "/images/hospitality-transformation.jpg",
  heroMobile: "/images/hero mobile.jpg",
  hero2Main: "/images/hero2.jpg",
  heroPackard: "/images/hero image for promo packard.jpg",
  heroBg: "/images/hero-bg.svg",
  mobileHero: "/images/mobile hero.jpg",
  behindTheScene: "/images/behind the scene.jpg",
  brandedClock: "/images/branded clock.jpg",
};

export const productionFacilitiesImages = {
  digital: "/images/digital printing.jpg",
  offset: "/images/offset printing.jpg",
  large: "/images/large format printing.jpg",
  packaging: "/images/packaging.jpg",
  signage: "/images/illuminated signage.jpg",
  vehicle: "/images/vehicle branding.jpg",
  promo: "/images/screen printing.jpg",
  embroidery: "/images/embroidery service.jpg",
  dtf: "/images/dtf printing.jpg",
  quality: "/images/quality inspection scene printing.jpg",
};

export const portfolioImageMap: Record<string, { image: string; gallery: string[] }> = {
  "crdb-branch-signage": {
    image: "/images/crdb-banking-branding.jpg",
    gallery: ["/images/crdb-banking-branding.jpg", "/images/crdb-brand-transformation.jpg", "/images/illuminated signage.jpg", "/images/led illuminated sign.jpg", "/images/3d sign.jpg", "/images/reception  wall sign.jpg"],
  },
  "vodacom-vehicle-fleet": {
    image: "/images/vehicle branding.jpg",
    gallery: ["/images/vehicle branding.jpg", "/images/wheel cover.jpg", "/images/vodacom-billboard.jpg", "/images/outdoor-advertising.jpg"],
  },
  "azam-50k-notebooks": {
    image: "/images/note book.jpg",
    gallery: ["/images/note book.jpg", "/images/printing-stationery-scene.jpg", "/images/offset printing.jpg", "/images/letter head.jpg"],
  },
  "serena-resort-packaging": {
    image: "/images/serena-hotel-branding.jpg",
    gallery: ["/images/serena-hotel-branding.jpg", "/images/packaging.jpg", "/images/luxury-hotel-branding.jpg", "/images/product package.jpg", "/images/certificate holder.jpg"],
  },
  "dangote-truck-fleet": {
    image: "/images/bakhresa-industrial-branding.jpg",
    gallery: ["/images/bakhresa-industrial-branding.jpg", "/images/vehicle branding.jpg", "/images/manufacturing-industry.jpg", "/images/wheel cover.jpg"],
  },
  "safaricom-exhibition": {
    image: "/images/exhibition stand.jpg",
    gallery: ["/images/exhibition stand.jpg", "/images/backdrop banner.jpg", "/images/x-banner.jpg", "/images/teardrop banner.jpg", "/images/promotional table.jpg"],
  },
  "unicef-campaign": {
    image: "/images/promo-campaign-tanzania.jpg",
    gallery: ["/images/promo-campaign-tanzania.jpg", "/images/backpack.jpg", "/images/round neck t-shirt.jpg", "/images/cap.jpg", "/images/conference bag.jpg"],
  },
  "university-textbooks": {
    image: "/images/education-sector.jpg",
    gallery: ["/images/education-sector.jpg", "/images/offset printing.jpg", "/images/printing-stationery-scene.jpg", "/images/executive diary.jpg"],
  },
  "hyatt-signage-system": {
    image: "/images/luxury-hotel-branding.jpg",
    gallery: ["/images/luxury-hotel-branding.jpg", "/images/sea-cliff-signage.jpg", "/images/wayfinder sign.jpg", "/images/reception  wall sign.jpg", "/images/3d sign2.jpg"],
  },
  "azam-beverage-packaging": {
    image: "/images/tbl-beverage-branding.jpg",
    gallery: ["/images/tbl-beverage-branding.jpg", "/images/packaging labels.jpg", "/images/packaging.jpg", "/images/product package.jpg"],
  },
  "nmb-corporate-stationery": {
    image: "/images/nmb-bank-evolution.jpg",
    gallery: ["/images/nmb-bank-evolution.jpg", "/images/business card2.jpg", "/images/letter head.jpg", "/images/envelop.jpg", "/images/corporate business card.jpg"],
  },
  "airtel-billboard": {
    image: "/images/outdoor-advertising.jpg",
    gallery: ["/images/outdoor-advertising.jpg", "/images/vodacom-billboard.jpg", "/images/large format printing.jpg", "/images/offset printing.jpg"],
  },
};

categoryConfig.forEach((c) => {
  c.count = productCatalog.filter((p) => p.category === c.name).length;
});
