import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: "digital-printing",
    slug: "digital-printing",
    title: "Digital Printing",
    image: "/images/service-digital-printing.jpg",
    shortDescription:
      "High-resolution, fast-turnaround digital printing for business cards, flyers, brochures, posters, stickers and stationery.",
    description:
      "Premium digital printing on state-of-the-art HP Indigo and Konica Minolta presses. From 1 unit to 100,000 units, with same-day turnaround on most stationery products. CMYK + spot white, gold and silver inks available for luxury finishes.",
    hero: "Premium digital printing at production speed.",
    icon: "M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m0 0a48.159 48.159 0 0110.5 0m-10.5 0V4.875c0-.621.504-1.125 1.125-1.125h8.25c.621 0 1.125.504 1.125 1.125v3.659",
    features: [
      "Business Cards (Standard, Premium, Magnetic, Foil, Plastic, Metal)",
      "Flyers & Leaflets (A4, A5, A6, DL, custom sizes)",
      "Brochures (Bi-fold, Tri-fold, Saddle-stitched, Perfect-bound)",
      "Posters (A3, A2, A1, A0, custom)",
      "Catalogues & Lookbooks",
      "Stickers & Labels (Die-cut, Kiss-cut, Sheet, Roll)",
      "Menus (Laminated, Foil-stamped, Multi-language)",
      "Certificates & Diplomas",
      "Letterheads & Compliment Slips",
      "ID Cards & Access Badges",
      "Calendars (Wall, Desk, Pocket, Branded)",
      "Greeting Cards & Invitations",
    ],
    products: [
      {
        id: "business-cards",
        slug: "business-cards",
        name: "Business Cards",
        description: "Premium 350gsm+ business cards with matte, gloss, soft-touch or velvet lamination. Optional foil stamping, spot UV, embossing and edge painting.",
        image: "/images/products/business-cards.jpg",
        startingPrice: 18000,
        minQty: 100,
        leadTime: "Same day – 24 hours",
        sizes: ["85 × 55mm (standard)", "90 × 55mm", "Custom"],
        materials: ["300gsm Art Card", "350gsm Art Card", "400gsm Cotton", "Recycled Kraft", "Plastic (transparent, white, frosted)", "Brushed Metal"],
        features: ["Matte / Gloss / Soft-touch lamination", "Spot UV, Gold / Silver foil", "Embossing & debossing", "Edge painting (colored edges)", "Rounded corners"],
        category: "Digital Printing",
      },
      {
        id: "flyers",
        slug: "flyers",
        name: "Flyers & Leaflets",
        description: "High-impact A4, A5, A6 and DL flyers in full color. Single or double-sided with optional folding.",
        image: "/images/products/flyers.jpg",
        startingPrice: 25000,
        minQty: 100,
        leadTime: "24–48 hours",
        sizes: ["A4 (210×297mm)", "A5 (148×210mm)", "A6 (105×148mm)", "DL (99×210mm)", "Custom"],
        materials: ["130gsm Gloss Art", "150gsm Gloss Art", "170gsm Silk", "200gsm Card"],
        features: ["Full color CMYK", "Single or double-sided", "Scoring & folding", "Bulk pricing for 5,000+ units"],
        category: "Digital Printing",
      },
      {
        id: "brochures",
        slug: "brochures",
        name: "Brochures",
        description: "Bi-fold, tri-fold, gate-fold and multi-page brochures. Perfect for product catalogues, service menus and corporate profiles.",
        image: "/images/products/brochures.jpg",
        startingPrice: 75000,
        minQty: 50,
        leadTime: "3–5 business days",
        sizes: ["A4", "A5", "Letter (US)", "Square 210×210mm", "Custom"],
        materials: ["150gsm Silk", "170gsm Silk", "250gsm Cover + 150gsm Inner", "Recycled"],
        features: ["Saddle-stitched", "Perfect-bound", "Wiro-bound", "Foil & Spot UV options"],
        category: "Digital Printing",
      },
      {
        id: "posters",
        slug: "posters",
        name: "Posters",
        description: "Vivid full-color posters for promotions, events, retail and indoor branding. Waterproof and UV-stable options.",
        image: "/images/products/posters.jpg",
        startingPrice: 8000,
        minQty: 10,
        leadTime: "24 hours",
        sizes: ["A3 (297×420mm)", "A2 (420×594mm)", "A1 (594×841mm)", "A0 (841×1189mm)", "Custom"],
        materials: ["200gsm Poster Paper", "Premium Photo Paper", "PVC Banner (for outdoor)"],
        features: ["Photographic quality", "Mounting on foam-board or corflute", "Lamination options"],
        category: "Digital Printing",
      },
      {
        id: "stickers-labels",
        slug: "stickers-labels",
        name: "Stickers & Labels",
        description: "Custom die-cut stickers, kiss-cut sticker sheets, and product label rolls. Waterproof vinyl, transparent and kraft options.",
        image: "/images/products/stickers.jpg",
        startingPrice: 15000,
        minQty: 100,
        leadTime: "2–4 business days",
        sizes: ["Any custom shape", "Standard sizes available", "Sheet (A4 / A5)", "Roll (any length)"],
        materials: ["White Vinyl (waterproof)", "Transparent Vinyl", "Holographic Vinyl", "Kraft Paper", "Chrome / Mirror"],
        features: ["Die-cut to any shape", "Kiss-cut sheets", "Indoor & outdoor use", "Food-safe options"],
        category: "Digital Printing",
      },
      {
        id: "menus",
        slug: "menus",
        name: "Restaurant Menus",
        description: "Laminated menus, single-page menus, multi-page booklets and luxury foil-stamped menus for fine dining.",
        image: "/images/products/menus.jpg",
        startingPrice: 35000,
        minQty: 25,
        leadTime: "3–5 business days",
        sizes: ["A4", "A5", "DL (folded)", "Custom"],
        materials: ["250gsm Silk", "300gsm Silk", "Laminated (matte/gloss)", "Wood / Acrylic (premium)"],
        features: ["Matte or gloss lamination", "Foil stamping", "Wiro or spiral binding", "Wipe-clean surfaces"],
        category: "Digital Printing",
      },
      {
        id: "certificates",
        slug: "certificates",
        name: "Certificates & Diplomas",
        description: "Elegant award certificates, diplomas and achievement letters with optional gold borders, embossed seals and signature panels.",
        image: "/images/products/certificates.jpg",
        startingPrice: 45000,
        minQty: 50,
        leadTime: "3–5 business days",
        sizes: ["A4", "A3", "Letter", "Custom"],
        materials: ["250gsm Gold-Trimmed Card", "300gsm Parchment-look", "Cotton Paper", "Velvet Laminated"],
        features: ["Gold/Silver foil borders", "Variable data printing (names)", "Numbered series", "Matching presentation folders"],
        category: "Digital Printing",
      },
      {
        id: "letterheads",
        slug: "letterheads",
        name: "Letterheads & Stationery",
        description: "Complete corporate stationery sets: letterheads, compliment slips, envelopes, and matching folders.",
        image: "/images/products/letterheads.jpg",
        startingPrice: 32000,
        minQty: 500,
        leadTime: "3–5 business days",
        sizes: ["A4 (Letterhead)", "DL (Compliment Slip)", "C5 / C4 (Envelopes)"],
        materials: ["100gsm Bond", "120gsm Bond", "Watermarked Bond"],
        features: ["Single or full color", "Watermarking", "Matching envelopes", "Bulk pricing for 5,000+"],
        category: "Digital Printing",
      },
    ],
    faqs: [
      {
        q: "What is the minimum order quantity for digital printing?",
        a: "For most stationery products (business cards, flyers, posters) the minimum is just 100 units. We can also do single-unit premium business cards for executives. Bulk discounts kick in at 500+ units.",
      },
      {
        q: "How fast can I get business cards delivered?",
        a: "Standard business cards are produced and delivered within 24 hours in Dar es Salaam. Premium finishes (foil, spot UV, edge painting) take 2–3 business days. Same-day rush service is available for an additional fee.",
      },
      {
        q: "Do you provide design services?",
        a: "Yes — our in-house Design Studio can create your artwork from scratch, refine your existing files, or convert logos to print-ready format. Design fees start from TZS 50,000 for stationery sets.",
      },
      {
        q: "Can you print on unusual materials?",
        a: "Absolutely. We print on vinyl, transparent film, kraft, metallic paper, cotton, plastic (PVC, PET), brushed metal, wood and acrylic. Contact us with your requirement.",
      },
    ],
    color: "from-blue-500/20 to-cyan-600/10",
  },
  {
    id: "offset-printing",
    slug: "offset-printing",
    title: "Offset Printing",
    image: "/images/service-offset-printing.jpg",
    shortDescription:
      "Bulk-run offset printing for books, magazines, annual reports and large-volume brochures. Heidelberg 4-color + 2-color press capacity.",
    description:
      "Industrial-grade offset printing on Heidelberg Speedmaster presses for high-volume, color-critical jobs. Ideal for books, magazines, annual reports, company profiles, educational materials and bulk commercial print runs from 2,000 to 1,000,000+ units.",
    hero: "Industrial offset printing for volume runs.",
    icon: "M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25",
    features: [
      "Books (Textbooks, Novels, Religious, Children's)",
      "Magazines & Periodicals",
      "Annual Reports & Financial Statements",
      "Bulk Brochures (5,000+ units)",
      "Company Profiles",
      "Educational Materials & Workbooks",
      "Newspapers & Newsletters",
      "Catalogues (Multi-page, 200+ pages)",
      "Manuals & Technical Documents",
      "Diaries & Planners (corporate)",
    ],
    products: [
      {
        id: "books",
        slug: "books",
        name: "Books",
        description: "Hardcover, softcover, perfect-bound and saddle-stitched books. From short-run novels to 50,000-copy textbooks.",
        image: "/images/products/books.jpg",
        startingPrice: 4500,
        minQty: 200,
        leadTime: "7–14 business days",
        sizes: ["A5 (148×210mm)", "B5 (176×250mm)", "A4 (210×297mm)", "6×9 inches", "Custom"],
        materials: ["70gsm Book Paper", "80gsm Book Paper", "130gsm Cover (Softcover)", "Hardcover (Casebound)"],
        features: ["Perfect binding", "Saddle stitching", "Hardcover (casebound)", "Section-sewn signatures", "Foil title on cover"],
        category: "Offset Printing",
      },
      {
        id: "magazines",
        slug: "magazines",
        name: "Magazines & Periodicals",
        description: "Multi-page full-color magazines with perfect binding or saddle-stitch. Gloss or matte lamination on cover.",
        image: "/images/products/magazines.jpg",
        startingPrice: 3800,
        minQty: 500,
        leadTime: "10–14 business days",
        sizes: ["A4 (210×297mm)", "210×280mm (standard)", "230×300mm", "Custom"],
        materials: ["130gsm Gloss Art (inner)", "170gsm Gloss Art (inner)", "250gsm Cover (laminated)"],
        features: ["Perfect binding", "Saddle-stitch", "Cover lamination", "Variable data for subscriber copies"],
        category: "Offset Printing",
      },
      {
        id: "annual-reports",
        slug: "annual-reports",
        name: "Annual Reports",
        description: "Premium annual reports and financial statements for corporations, banks, NGOs and government institutions. Corporate-quality finish.",
        image: "/images/products/annual-reports.jpg",
        startingPrice: 12000,
        minQty: 100,
        leadTime: "7–12 business days",
        sizes: ["A4 (210×297mm)", "210×280mm", "210×297mm landscape"],
        materials: ["150gsm Silk (inner)", "250gsm Silk + Lamination (cover)", "Recycled (eco option)"],
        features: ["Spot UV on cover", "Foil stamped logo", "Section dividers", "Custom slipcase available"],
        category: "Offset Printing",
      },
      {
        id: "bulk-brochures",
        slug: "bulk-brochures",
        name: "Bulk Brochures",
        description: "5,000+ unit brochure runs at the lowest per-unit cost. Bi-fold, tri-fold, multi-page, with or without lamination.",
        image: "/images/products/bulk-brochures.jpg",
        startingPrice: 220,
        minQty: 5000,
        leadTime: "7–10 business days",
        sizes: ["A4", "A5", "DL", "Square 210×210mm"],
        materials: ["130gsm Gloss Art", "150gsm Gloss Art", "170gsm Silk"],
        features: ["Self-cover", "Plus-cover (heavier cover)", "Bi-fold, tri-fold, gate-fold", "Spot UV / foil upgrade"],
        category: "Offset Printing",
      },
      {
        id: "company-profiles",
        slug: "company-profiles",
        name: "Company Profiles",
        description: "Multi-page corporate profile documents for pitches, investor relations, banks, and B2B credibility.",
        image: "/images/products/company-profiles.jpg",
        startingPrice: 9500,
        minQty: 100,
        leadTime: "7–10 business days",
        sizes: ["A4", "Square 210×210mm", "Letter (US)"],
        materials: ["170gsm Silk", "250gsm Cover + 150gsm Inner", "Recycled"],
        features: ["Perfect binding", "Saddle-stitch", "Spot UV cover finish", "Digital variable data"],
        category: "Offset Printing",
      },
      {
        id: "educational-materials",
        slug: "educational-materials",
        name: "Educational Materials",
        description: "Textbooks, workbooks, exercise books, revision booklets, exam papers. Optimized for cost and durability.",
        image: "/images/products/educational.jpg",
        startingPrice: 350,
        minQty: 1000,
        leadTime: "10–21 business days",
        sizes: ["A4", "A5", "B5", "Custom"],
        materials: ["60gsm Bible Paper", "70gsm Book Paper", "80gsm Book Paper", "Cover board"],
        features: ["Single or two-color", "Full color", "Numbered or perforated sections", "Spiral or wiro binding"],
        category: "Offset Printing",
      },
    ],
    faqs: [
      {
        q: "What is the break-even point for offset vs digital?",
        a: "Offset becomes more cost-effective than digital at around 1,000–2,000 units depending on the product. Below that, digital is faster and more economical.",
      },
      {
        q: "Can you handle very large print runs?",
        a: "Yes — we regularly produce 100,000+ unit runs. Our Heidelberg presses can run continuously with auto-plate loading for maximum efficiency.",
      },
      {
        q: "Do you offer Pantone color matching?",
        a: "Absolutely. We can mix and match Pantone spot colors, and provide color proofs before full production runs.",
      },
      {
        q: "What's the turnaround for a 50,000 book run?",
        a: "Standard lead time is 14–21 business days including binding. We can expedite to 10 days for time-sensitive textbook launches.",
      },
    ],
    color: "from-emerald-500/20 to-teal-600/10",
  },
  {
    id: "large-format-printing",
    slug: "large-format-printing",
    title: "Large Format Printing",
    image: "/images/service-large-format-printing.jpg",
    shortDescription:
      "Banners, roll-up stands, backdrops, billboards, wall and window graphics. Indoor and outdoor solutions with installation.",
    description:
      "Industrial large-format printing up to 5 meters wide. Solvent, eco-solvent, UV and latex inks for every environment — indoor retail, outdoor billboards, vehicle wraps, and architectural wraps. Complete with site survey, design, production and certified installation.",
    hero: "Big format. Bigger impact.",
    icon: "M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 3m8.5-3l1 3m0 0l.5 1.5m-.5-1.5h-9.5m0 0l-.5 1.5",
    features: [
      "PVC Banners (any size, hemmed & eyeleted)",
      "Roll-up / Pull-up Banners (retractable)",
      "X / L / Pop-up Backdrops",
      "Billboards (skinned, vinyl, digital-ready)",
      "Wall Graphics & Wallpaper (custom murals)",
      "Window Graphics & Perforated Vinyl",
      "Floor Graphics (anti-slip)",
      "Stretch Fabric Frames (SEG)",
      "Event Stage Backdrops",
      "Exhibition Panels",
    ],
    products: [
      {
        id: "pvc-banners",
        slug: "pvc-banners",
        name: "PVC Banners",
        description: "Heavy-duty outdoor PVC banners for events, sales, construction sites, roadshows and shopfronts. Hemmed with metal eyelets.",
        image: "/images/products/pvc-banners.jpg",
        startingPrice: 12000,
        minQty: 1,
        leadTime: "1–3 business days",
        sizes: ["Any size (max 5m wide seamless)"],
        materials: ["440gsm PVC (standard)", "510gsm Premium PVC", "Mesh PVC (wind-resistant)", "Blockout (double-sided)"],
        features: ["High-frequency welded edges", "Brass / plastic eyelets", "Pole pockets", "Wind-cut mesh option"],
        category: "Large Format",
      },
      {
        id: "rollup-banners",
        slug: "rollup-banners",
        name: "Roll-up Banners",
        description: "Self-standing retractable roll-up banner stands — the classic trade show and event workhorse.",
        image: "/images/products/rollup.jpg",
        startingPrice: 55000,
        minQty: 1,
        leadTime: "2–3 business days",
        sizes: ["85 × 200cm (standard)", "100 × 200cm (wide)", "120 × 200cm (extra wide)", "150 × 200cm (premium)"],
        materials: ["Premium anti-curl polyester film", "440gsm PVC", "Knitted polyester fabric"],
        features: ["Anodized aluminum base", "Carrying bag included", "Pole support", "Replacement print graphics"],
        category: "Large Format",
      },
      {
        id: "backdrops",
        slug: "backdrops",
        name: "Event Backdrops",
        description: "Step-and-repeat backdrops, pop-up displays, fabric tension frames and stage backdrops for events, conferences and exhibitions.",
        image: "/images/products/backdrops.jpg",
        startingPrice: 145000,
        minQty: 1,
        leadTime: "3–5 business days",
        sizes: ["2 × 2.3m (pop-up)", "3 × 2.3m (pop-up)", "3 × 4m (custom)", "Any custom size"],
        materials: ["Stretch fabric (SEG frame)", "Tension fabric", "PVC with frame", "Vinyl adhesive"],
        features: ["Lightweight aluminum frame", "Tool-free assembly", "Carrying case", "Washable fabric graphics"],
        category: "Large Format",
      },
      {
        id: "billboards",
        slug: "billboards",
        name: "Billboards",
        description: "Production and installation of vinyl billboard skins for static structures and rotating billboard sites.",
        image: "/images/products/billboards.jpg",
        startingPrice: 350000,
        minQty: 1,
        leadTime: "5–7 business days",
        sizes: ["6 × 3m (standard)", "8 × 4m (medium)", "12 × 5m (large)", "Custom"],
        materials: ["510gsm Frontlit PVC", "Blockout (double-sided)", "Reflective vinyl"],
        features: ["Full installation", "Site survey", "Re-skinning existing structures", "Wind-load certification"],
        category: "Large Format",
      },
      {
        id: "wall-graphics",
        slug: "wall-graphics",
        name: "Wall Graphics & Murals",
        description: "Custom-printed wall murals, brand walls, motivational graphics and decorative wallpaper for offices, retail, schools and clinics.",
        image: "/images/products/wall-graphics.jpg",
        startingPrice: 8500,
        minQty: 1,
        leadTime: "5–7 business days",
        sizes: ["Any size (tiled)", "Custom panels", "Full-wall coverage"],
        materials: ["Premium self-adhesive vinyl", "Textured wallpaper (custom print)", "Fabric-backed vinyl"],
        features: ["Professional installation included", "Custom design service", "Removable / permanent options", "Anti-graffiti laminate"],
        category: "Large Format",
      },
      {
        id: "window-graphics",
        slug: "window-graphics",
        name: "Window Graphics",
        description: "Perforated window vinyl, frosted vinyl, clear vinyl and opaque window decals for shopfronts, offices and vehicles.",
        image: "/images/products/window-graphics.jpg",
        startingPrice: 6500,
        minQty: 1,
        leadTime: "3–5 business days",
        sizes: ["Any size", "Custom die-cut shapes", "Full window coverage"],
        materials: ["Perforated vinyl (one-way vision)", "Frosted etched vinyl", "Clear vinyl", "Static cling (removable)"],
        features: ["UV-stable inks", "Easy application", "Bubble-free installation", "Removable options"],
        category: "Large Format",
      },
    ],
    faqs: [
      {
        q: "Do you install outdoor banners?",
        a: "Yes — our certified installation teams handle everything from simple wall banners to complex scaffolding jobs for high-rise billboards. Site survey is free within Dar es Salaam.",
      },
      {
        q: "How long do outdoor banners last?",
        a: "Standard 440gsm PVC banners last 2–3 years outdoors with our UV-stable inks. Premium 510gsm with lamination lasts 4–5+ years.",
      },
      {
        q: "Can you wrap a vehicle with custom graphics?",
        a: "Absolutely. We handle full vehicle wraps, partial wraps, and decals using premium 3M and Avery Dennison vinyls with 5–7 year outdoor durability.",
      },
      {
        q: "What's the largest size you can print?",
        a: "Our printers handle up to 5 meters wide seamlessly. For larger surfaces we tile with minimal 2mm overlap, designed to be invisible after installation.",
      },
    ],
    color: "from-violet-500/20 to-purple-600/10",
  },
  {
    id: "packaging-printing",
    slug: "packaging-printing",
    title: "Packaging Printing",
    image: "/images/service-packaging-printing.jpg",
    shortDescription:
      "Custom product packaging, food-grade, cosmetic, pharmaceutical, retail boxes, labels and gift packaging.",
    description:
      "Full-service packaging — from structural design and dieline creation to offset and digital printing, finishing (foil, emboss, spot UV) and full assembly. Food-safe inks, FSC-certified board, and ECO-friendly options available.",
    hero: "Packaging that sells before the product does.",
    icon: "M21 7.5l-2.25-1.313M21 7.5v2.25m0-2.25-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3l2.25-1.313M12 12.75l-2.25-1.313M12 12.75V15m0 6.75l2.25-1.313M12 21.75V19.5m0 2.25-2.25-1.313m0-16.875L12 2.25l2.25 1.313M21 14.25v2.25l-2.25 1.313m-13.5 0L3 16.5v-2.25",
    features: [
      "Product Packaging (Rigid & Folding Cartons)",
      "Food Packaging (Food-safe certified)",
      "Cosmetic & Beauty Packaging",
      "Pharmaceutical Packaging (Tanzania FDA compliant)",
      "Retail Packaging (Shelf-ready boxes)",
      "Gift Boxes & Premium Packaging",
      "Labels & Sleeves (Shrink-sleeve)",
      "Bottle & Jar Labels",
      "Promotional / Mailer Boxes",
      "Corrugated Shipping Cartons",
    ],
    products: [
      {
        id: "folding-cartons",
        slug: "folding-cartons",
        name: "Folding Cartons",
        description: "Custom-printed folding cartons for retail, food, cosmetics and consumer goods. Litho-laminated or digital print.",
        image: "/images/products/cartons.jpg",
        startingPrice: 250,
        minQty: 1000,
        leadTime: "10–14 business days",
        sizes: ["Custom (dieline required)", "Standard sizes available"],
        materials: ["SBS (Solid Bleached Sulfate)", "CCNB (Clay-Coated News Back)", "FSC-certified board", "Recycled board"],
        features: ["Full CMYK + spot colors", "Matte / gloss lamination", "Spot UV, foil stamping", "Embossing & debossing"],
        category: "Packaging",
      },
      {
        id: "food-packaging",
        slug: "food-packaging",
        name: "Food Packaging",
        description: "Food-safe packaging for bakeries, restaurants, takeaway, tea, coffee, spices, snacks and confectionery.",
        image: "/images/products/food-packaging.jpg",
        startingPrice: 180,
        minQty: 1000,
        leadTime: "10–14 business days",
        sizes: ["Custom", "Standard pizza boxes", "Burger boxes", "Cup sleeves", "Paper bags"],
        materials: ["Food-grade kraft", "PE-coated board", "Compostable PLA lining", "Grease-proof paper"],
        features: ["Food-safe inks", "FDA / TBS compliant", "Microwave-safe options", "Compostable options"],
        category: "Packaging",
      },
      {
        id: "cosmetic-packaging",
        slug: "cosmetic-packaging",
        name: "Cosmetic Packaging",
        description: "Premium cosmetic packaging — luxury cartons, rigid boxes, sample boxes, fragrance sleeves and skincare tubes.",
        image: "/images/products/cosmetic.jpg",
        startingPrice: 450,
        minQty: 500,
        leadTime: "14–21 business days",
        sizes: ["Custom dieline", "Standard cosmetic sizes"],
        materials: ["Rigid board (grayboard wrapped)", "Premium SBS", "Soft-touch laminated", "Pearl / metallic paper"],
        features: ["Hot foil stamping", "Spot UV + soft-touch laminate", "Embossing", "Flocked interior", "Magnetic closure"],
        category: "Packaging",
      },
      {
        id: "pharmaceutical-packaging",
        slug: "pharmaceutical-packaging",
        name: "Pharmaceutical Packaging",
        description: "TMDA-compliant pharmaceutical packaging — cartons, inserts, labels and patient information leaflets.",
        image: "/images/products/pharma.jpg",
        startingPrice: 280,
        minQty: 1000,
        leadTime: "14–21 business days",
        sizes: ["Custom (dieline)", "Standard pharmaceutical formats"],
        materials: ["Pharmaceutical-grade SBS", "FSC-certified", "Tamper-evident board"],
        features: ["TMDA compliant", "Variable batch data", "Barcode / QR integration", "Braille options"],
        category: "Packaging",
      },
      {
        id: "retail-packaging",
        slug: "retail-packaging",
        name: "Retail Packaging",
        description: "Shelf-ready retail packaging — counter display units, shelf-ready trays, gift packs and blister cards.",
        image: "/images/products/retail.jpg",
        startingPrice: 320,
        minQty: 500,
        leadTime: "10–18 business days",
        sizes: ["Custom", "Standard retail sizes"],
        materials: ["Corrugated (E-flute, B-flute)", "Folding boxboard", "Display board"],
        features: ["Shelf-ready design", "Pop-up displays", "Easy-open tear strips", "Full color print"],
        category: "Packaging",
      },
      {
        id: "gift-boxes",
        slug: "gift-boxes",
        name: "Gift Boxes & Premium Packaging",
        description: "Magnetic closure rigid gift boxes, drawer boxes, lift-off lid boxes for corporate gifting and luxury retail.",
        image: "/images/products/gift-boxes.jpg",
        startingPrice: 1800,
        minQty: 100,
        leadTime: "14–21 business days",
        sizes: ["Custom sizes"],
        materials: ["Rigid grayboard", "Pearl paper wrap", "Velvet-touch laminate", "Leather-look paper"],
        features: ["Magnetic closure", "Ribbon pull", "Custom foam insert", "Hot foil logo", "Fabric lining"],
        category: "Packaging",
      },
    ],
    faqs: [
      {
        q: "Do you provide structural design for packaging?",
        a: "Yes — our packaging engineers create custom dielines from scratch, recommend materials, and produce 3D mockups before production.",
      },
      {
        q: "Are your food packaging inks safe?",
        a: "Absolutely. We use low-migration, food-contact-safe inks compliant with TBS and EU food safety standards.",
      },
      {
        q: "What's the minimum order for custom packaging?",
        a: "For offset-printed folding cartons the minimum is typically 1,000 units. For digital packaging (premium runs, samples) we can produce from 100 units.",
      },
      {
        q: "Can you do sustainable / eco packaging?",
        a: "Yes — we offer FSC-certified board, recycled materials, soy-based inks, and fully compostable PLA-lined options for food packaging.",
      },
    ],
    color: "from-amber-500/20 to-orange-600/10",
  },
  {
    id: "signage-solutions",
    slug: "signage-solutions",
    title: "Signage Solutions",
    image: "/images/service-signage-solutions.jpg",
    shortDescription:
      "Shop signboards, LED signs, building signage, office signage, wayfinding systems, lightboxes and architectural signs.",
    description:
      "Complete signage solutions from design and engineering to fabrication and installation. We manufacture in-house — channel letters, lightboxes, monoliths, pylons, totems, wayfinding systems, interior and exterior signage for retail, corporate, hospitality, healthcare and education.",
    hero: "Signage that defines your space.",
    icon: "M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z",
    features: [
      "Shop Signboards (Acrylic, Aluminum, ACP)",
      "LED Signage & Channel Letters",
      "Building Signage & Tower Signs",
      "Office Signage & Reception Branding",
      "Wayfinding Systems",
      "Lightboxes & Illuminated Signs",
      "Monolith / Pylon / Totem Signs",
      "3D Acrylic Letters",
      "Stainless Steel Lettering",
      "Wooden / Rustic Signage",
    ],
    products: [
      {
        id: "shop-signboards",
        slug: "shop-signboards",
        name: "Shop Signboards",
        description: "Aluminum composite (ACP), acrylic and illuminated shop signboards for retail, restaurants and commercial buildings.",
        image: "/images/products/shop-signboard.jpg",
        startingPrice: 180000,
        minQty: 1,
        leadTime: "5–10 business days",
        sizes: ["Custom (any size)"],
        materials: ["ACP (Aluminum Composite Panel)", "Acrylic (clear, opal, colored)", "Stainless steel (mirror, brushed)", "MDF / wood"],
        features: ["3D lettering", "LED illumination (front/side/back-lit)", "UV-printed graphics", "Weatherproof 5+ years"],
        category: "Signage",
      },
      {
        id: "led-signs",
        slug: "led-signs",
        name: "LED Signs & Channel Letters",
        description: "Fabricated channel letters with LED illumination, programmed LED message boards, and neon-style LED signs.",
        image: "/images/products/led-signs.jpg",
        startingPrice: 85000,
        minQty: 1,
        leadTime: "7–14 business days",
        sizes: ["Custom letter heights", "From 10cm to 200cm+"],
        materials: ["Aluminum", "Stainless steel", "Acrylic face", "Halo-lit (reverse channel)"],
        features: ["Front-lit, side-lit or halo-lit", "RGB color-changing options", "Programmable message displays", "5+ year LED lifespan"],
        category: "Signage",
      },
      {
        id: "building-signage",
        slug: "building-signage",
        name: "Building & Tower Signage",
        description: "Large-scale building signage for offices, banks, hotels and corporate headquarters. Engineering-certified.",
        image: "/images/products/building-signage.jpg",
        startingPrice: 850000,
        minQty: 1,
        leadTime: "14–28 business days",
        sizes: ["Custom (rooftop, facade, tower)"],
        materials: ["Structural steel frame", "Aluminum cladding", "ACP, acrylic, LED", "Tension fabric frame"],
        features: ["Wind-load engineering", "Maintenance access design", "Energy-efficient LEDs", "Permit & council approval support"],
        category: "Signage",
      },
      {
        id: "office-signage",
        slug: "office-signage",
        name: "Office Signage & Reception",
        description: "Interior office signage — reception logos, room name plates, floor directories, glass manifestations and wayfinding.",
        image: "/images/products/office-signage.jpg",
        startingPrice: 35000,
        minQty: 1,
        leadTime: "5–10 business days",
        sizes: ["Custom", "Standard office sign sizes"],
        materials: ["Acrylic (clear, frosted, colored)", "Stainless steel (brushed, mirror)", "Aluminum", "Vinyl (for glass)"],
        features: ["3D logo reception signs", "Frosted glass manifestations", "Engraved name plates", "ADA / accessibility compliant"],
        category: "Signage",
      },
      {
        id: "wayfinding",
        slug: "wayfinding",
        name: "Wayfinding Systems",
        description: "Complete wayfinding systems for hospitals, schools, malls, hotels, airports and corporate campuses.",
        image: "/images/products/wayfinding.jpg",
        startingPrice: 45000,
        minQty: 10,
        leadTime: "14–28 business days",
        sizes: ["Custom system", "Standard modules"],
        materials: ["Aluminum", "Acrylic", "Stainless steel", "Backlit options"],
        features: ["Modular design", "Multi-language", "Map boards", "Directional + identification + regulatory"],
        category: "Signage",
      },
      {
        id: "lightboxes",
        slug: "lightboxes",
        name: "Lightboxes & Illuminated Signs",
        description: "Backlit fabric lightboxes, snap-frame lightboxes, edge-lit LED panels and menu boards for retail and restaurants.",
        image: "/images/products/lightboxes.jpg",
        startingPrice: 65000,
        minQty: 1,
        leadTime: "5–10 business days",
        sizes: ["A1 (594×841mm)", "A0 (841×1189mm)", "Custom", "Standard lightbox modules"],
        materials: ["Aluminum frame", "SEG fabric graphics", "Backlit film", "LED edge-lit acrylic"],
        features: ["Even illumination", "Replaceable graphics", "Energy-efficient LEDs", "Wall-mounted or suspended"],
        category: "Signage",
      },
    ],
    faqs: [
      {
        q: "Do you handle installation?",
        a: "Yes — we have certified installation teams with rope-access, scaffolding and boom-lift capability for any height. All installations come with a 2-year workmanship warranty.",
      },
      {
        q: "How long does a shop signboard last?",
        a: "Our illuminated signboards typically last 5–7 years outdoors with proper maintenance. LED modules are rated for 50,000+ hours.",
      },
      {
        q: "Can you help with council / municipal approvals?",
        a: "Yes, we assist with permit applications, structural engineering certification and landlord approvals for installations.",
      },
      {
        q: "Do you provide design and 3D mockups?",
        a: "Yes — every signage project starts with a free site survey, design concept and 3D mockup before production begins.",
      },
    ],
    color: "from-rose-500/20 to-pink-600/10",
  },
  {
    id: "vehicle-branding",
    slug: "vehicle-branding",
    title: "Vehicle Branding",
    image: "/images/service-vehicle-branding.jpg",
    shortDescription:
      "Car, bus, fleet and truck branding with premium vinyl. Full wraps, partial wraps and decal applications.",
    description:
      "Mobile advertising specialists. From single executive car wraps to 100-vehicle fleet rollouts. We use premium 3M and Avery Dennison cast vinyls with UV-stable inks and anti-laminate protection for 5–7 year outdoor durability.",
    hero: "Your fleet is a moving billboard.",
    icon: "M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12",
    features: [
      "Car Branding (Sedans, SUVs, Pickups)",
      "Bus Branding (Full wrap, partial wrap, decals)",
      "Fleet Branding (Multi-vehicle rollouts)",
      "Truck Branding (Box trucks, trailers, tankers)",
      "Motorcycle & Bodaboda Branding",
      "Taxi & Ride-hailing Branding",
      "Construction Equipment Branding",
      "Custom Vehicle Decals & Graphics",
    ],
    products: [
      {
        id: "car-branding",
        slug: "car-branding",
        name: "Car Branding",
        description: "Premium cast vinyl car wraps and decals. Full wrap, half wrap, or strategic decal placement.",
        image: "/images/products/car-branding.jpg",
        startingPrice: 350000,
        minQty: 1,
        leadTime: "2–4 business days",
        sizes: ["Custom to vehicle", "Full wrap", "Half wrap", "Decal package"],
        materials: ["3M IJ180Cv3 (premium cast)", "Avery Dennison MPI 1105", "ORACAL 970RA", "Anti-graffiti laminate"],
        features: ["5–7 year outdoor durability", "UV-stable", "Bubble-free install", "Removable without residue"],
        category: "Vehicle Branding",
      },
      {
        id: "bus-branding",
        slug: "bus-branding",
        name: "Bus Branding",
        description: "Full and partial bus branding for shuttle buses, public transport and corporate coaches.",
        image: "/images/products/bus-branding.jpg",
        startingPrice: 1500000,
        minQty: 1,
        leadTime: "3–7 business days",
        sizes: ["Full bus wrap", "Half bus", "Rear advertising panel", "Side advertising panels"],
        materials: ["3M IJ180Cv3", "Avery Dennison", "Anti-graffiti laminate"],
        features: ["Heavy-duty installation", "Reinforced edges", "Designed for high-frequency wash", "5+ year durability"],
        category: "Vehicle Branding",
      },
      {
        id: "fleet-branding",
        slug: "fleet-branding",
        name: "Fleet Branding Programs",
        description: "Multi-vehicle fleet rollouts with consistent brand standards, color management and structured deployment.",
        image: "/images/products/fleet.jpg",
        startingPrice: 320000,
        minQty: 5,
        leadTime: "Project-based",
        sizes: ["Mixed fleet sizes"],
        materials: ["Premium cast vinyl", "Anti-graffiti laminate", "Reflective options"],
        features: ["Brand standard compliance", "On-site fleet branding", "Replacement decal program", "Nationwide rollout"],
        category: "Vehicle Branding",
      },
      {
        id: "truck-branding",
        slug: "truck-branding",
        name: "Truck Branding",
        description: "Box trucks, delivery trucks, trailers and tankers — full wraps, side panels and tail graphics.",
        image: "/images/products/truck-branding.jpg",
        startingPrice: 1200000,
        minQty: 1,
        leadTime: "3–7 business days",
        sizes: ["Box truck full wrap", "Side panel only", "Tail gate graphic", "Custom"],
        materials: ["3M IJ180Cv3", "Heavy-duty laminate", "Reflective vinyl options"],
        features: ["High-mileage durability", "Anti-stone-chip laminate", "Reinforced door cut-outs", "Designed for highway speeds"],
        category: "Vehicle Branding",
      },
    ],
    faqs: [
      {
        q: "How long does a vehicle wrap last?",
        a: "Premium cast vinyl wraps (3M IJ180Cv3, Avery MPI 1105) with anti-graffiti laminate last 5–7 years in East African conditions with proper care.",
      },
      {
        q: "Can the wrap be removed without damaging paint?",
        a: "Yes. Our cast vinyls use removable adhesive. When professionally removed, the original paint underneath is preserved (and often better protected than unwrapped surfaces).",
      },
      {
        q: "Do you brand motorcycles and bodabodas?",
        a: "Yes — we specialize in delivery motorcycle branding for last-mile logistics, e-commerce and ride-hailing operators.",
      },
      {
        q: "Do you provide on-site fleet branding?",
        a: "For fleets of 5+ vehicles, we deploy mobile installation teams to your premises to minimize vehicle downtime.",
      },
    ],
    color: "from-red-500/20 to-rose-600/10",
  },
  {
    id: "promotional-products",
    slug: "promotional-products",
    title: "Promotional Products",
    image: "/images/service-promotional-products.jpg",
    shortDescription:
      "Branded merchandise — T-shirts, polos, caps, mugs, pens, diaries, keyholders, gift sets, water bottles.",
    description:
      "End-to-end branded merchandise. Source, customize, brand and deliver promotional products for trade shows, conferences, corporate gifts, school uniforms, sports teams and consumer promotions. Embroidery, screen printing, heat transfer, engraving, sublimation and UV DTF.",
    hero: "Merchandise that travels with your brand.",
    icon: "M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z",
    features: [
      "T-Shirts (Cotton, Polyester, Performance)",
      "Polo Shirts (Corporate & Sports)",
      "Caps (Baseball, Trucker, Beanie)",
      "Mugs (Ceramic, Travel, Glass)",
      "Pens (Metal, Plastic, Stylus)",
      "Diaries & Notebooks",
      "Key Holders (Metal, Leather, Acrylic)",
      "Gift Sets (Curated, Premium, Themed)",
      "Water Bottles (Stainless, Plastic, Glass)",
      "USB Drives, Power Banks, Tech Gifts",
    ],
    products: [
      {
        id: "tshirts",
        slug: "tshirts",
        name: "T-Shirts",
        description: "Custom branded T-shirts — screen print, heat transfer, DTG (direct-to-garment) and embroidery options.",
        image: "/images/products/tshirts.jpg",
        startingPrice: 8500,
        minQty: 25,
        leadTime: "5–10 business days",
        sizes: ["XS – 3XL (adult)", "Kids 2–14 yrs", "Custom sizes"],
        materials: ["100% Cotton (180gsm, 200gsm)", "Poly-Cotton blend", "Performance polyester (dri-fit)", "Organic cotton (eco)"],
        features: ["Screen print (1–6 colors)", "DTG (full color, no setup)", "Heat transfer vinyl", "Embroidery", "DTF (UV direct)"],
        category: "Promotional Products",
      },
      {
        id: "polo-shirts",
        slug: "polo-shirts",
        name: "Polo Shirts",
        description: "Corporate polo shirts with embroidery. Premium cotton, poly-cotton, and performance moisture-wicking options.",
        image: "/images/products/polo.jpg",
        startingPrice: 14000,
        minQty: 25,
        leadTime: "7–14 business days",
        sizes: ["S – 3XL", "Custom sizes"],
        materials: ["100% Pique Cotton", "Cotton-Poly blend", "Performance (dri-fit)", "Mercerized cotton (luxury)"],
        features: ["Embroidery (logo on chest, sleeve, back)", "Sublimation (full color all-over)", "Contrast collar & cuffs", "Custom buttons"],
        category: "Promotional Products",
      },
      {
        id: "caps",
        slug: "caps",
        name: "Caps & Headwear",
        description: "Custom caps — baseball, trucker, snapback, dad hat, beanie — embroidered or printed with your logo.",
        image: "/images/products/caps.jpg",
        startingPrice: 6500,
        minQty: 25,
        leadTime: "7–14 business days",
        sizes: ["One size fits most", "Adjustable snapback", "Velcro strap", "Fitted sizes (S–XL)"],
        materials: ["Cotton twill", "Polyester (performance)", "Cotton-Poly blend", "Acrylic (beanie)"],
        features: ["3D embroidered logo", "Flat embroidery", "Heat transfer (full color)", "Sublimation"],
        category: "Promotional Products",
      },
      {
        id: "mugs",
        slug: "mugs",
        name: "Branded Mugs",
        description: "Ceramic, travel and glass mugs with custom print. Sublimation, pad printing, color print and laser engraving.",
        image: "/images/products/mugs.jpg",
        startingPrice: 4500,
        minQty: 25,
        leadTime: "7–14 business days",
        sizes: ["11oz standard", "15oz large", "350ml travel mug", "500ml travel mug"],
        materials: ["White ceramic", "Color ceramic", "Stainless steel travel", "Borosilicate glass"],
        features: ["Full-wrap sublimation", "Single-side print", "Custom gift boxes", "Individual gift packaging"],
        category: "Promotional Products",
      },
      {
        id: "pens",
        slug: "pens",
        name: "Branded Pens",
        description: "Custom pens — metal, plastic, stylus, eco-friendly bamboo, recycled paper — laser engraved or pad printed.",
        image: "/images/products/pens.jpg",
        startingPrice: 950,
        minQty: 100,
        leadTime: "10–21 business days",
        sizes: ["Standard pen sizes"],
        materials: ["Metal (aluminum, brass)", "Plastic", "Bamboo", "Recycled paper", "Wheat-straw"],
        features: ["Laser engraving", "Pad printing (1–4 colors)", "Custom gift box", "Refillable ink options"],
        category: "Promotional Products",
      },
      {
        id: "diaries",
        slug: "diaries",
        name: "Diaries & Notebooks",
        description: "Branded diaries, notebooks, planners, journals with logo debossing, foil stamping or full-color print.",
        image: "/images/products/diaries.jpg",
        startingPrice: 6500,
        minQty: 50,
        leadTime: "14–21 business days",
        sizes: ["A5 (148×210mm)", "A4 (210×297mm)", "Pocket (90×140mm)", "B6"],
        materials: ["PU leather cover", "Hardcover", "Soft-touch laminate", "Recycled leather (eco)"],
        features: ["Debossed logo", "Foil stamped logo", "Full-color wrap print", "Pen loop", "Ribbon bookmark", "Elastic closure"],
        category: "Promotional Products",
      },
      {
        id: "key-holders",
        slug: "key-holders",
        name: "Key Holders",
        description: "Metal, leather, acrylic and wooden key holders with engraved, printed or embossed branding.",
        image: "/images/products/keyholders.jpg",
        startingPrice: 1800,
        minQty: 100,
        leadTime: "14–21 business days",
        sizes: ["Standard sizes", "Custom shapes"],
        materials: ["Stainless steel", "Brass", "Leather (PU or genuine)", "Acrylic", "Wood (engraved)"],
        features: ["Laser engraving", "UV color print", "Embossing", "Custom shapes (dieline)"],
        category: "Promotional Products",
      },
      {
        id: "gift-sets",
        slug: "gift-sets",
        name: "Corporate Gift Sets",
        description: "Curated gift sets in premium packaging — diaries, pens, mugs, USBs, power banks, and more.",
        image: "/images/products/gift-sets.jpg",
        startingPrice: 18000,
        minQty: 25,
        leadTime: "14–28 business days",
        sizes: ["Standard gift boxes", "Premium magnetic boxes", "Wooden boxes"],
        materials: ["Cardboard gift box", "Rigid magnetic box", "Wooden box (premium)", "Faux leather case"],
        features: ["Custom box design", "Mix and match products", "Ribbon & wrap", "Hand-written cards"],
        category: "Promotional Products",
      },
      {
        id: "water-bottles",
        slug: "water-bottles",
        name: "Branded Water Bottles",
        description: "Stainless steel, plastic and glass water bottles with logo laser engraving or UV print.",
        image: "/images/products/bottles.jpg",
        startingPrice: 5500,
        minQty: 50,
        leadTime: "14–21 business days",
        sizes: ["350ml", "500ml", "750ml", "1L"],
        materials: ["Stainless steel (single/double wall)", "Tritan plastic (BPA-free)", "Borosilicate glass", "Aluminum"],
        features: ["Laser engraving", "UV color print", "Full-wrap sublimation", "Powder-coated finishes"],
        category: "Promotional Products",
      },
    ],
    faqs: [
      {
        q: "What is the minimum order for branded T-shirts?",
        a: "Minimum is 25 units for screen print and embroidery, though pricing improves significantly at 50+ and 100+ units. DTG (full color) can run from a single unit.",
      },
      {
        q: "Can you help source unusual promotional products?",
        a: "Yes — we have direct factory relationships in China, UAE, Turkey and South Africa for sourcing custom promotional products. We can develop almost any item.",
      },
      {
        q: "Do you offer eco-friendly merchandise?",
        a: "Absolutely. We offer organic cotton apparel, recycled PET bottles, bamboo products, biodegradable pens, kraft notebooks and FSC-certified packaging.",
      },
      {
        q: "Can you handle last-minute orders?",
        a: "For urgent requirements we keep stock of plain T-shirts, polos, caps, mugs, pens and bottles that can be branded within 3–5 business days.",
      },
    ],
    color: "from-cyan-500/20 to-blue-600/10",
  },
  {
    id: "exhibition-events",
    slug: "exhibition-events",
    title: "Exhibition & Events",
    image: "/images/service-exhibition-branding.jpg",
    shortDescription:
      "Exhibition stands, pop-up displays, event branding, conference materials, registration counters and full event production.",
    description:
      "Modular and custom exhibition stands, pop-up displays, conference branding, registration desks, and complete event collateral. Design, fabrication, on-site setup and post-event storage available.",
    hero: "Make your event unforgettable.",
    icon: "M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 3m8.5-3l1 3m0 0l.5 1.5m-.5-1.5h-9.5m0 0l-.5 1.5m.75-9l3-3 2.148 2.148A12.061 12.061 0 0116.5 7.605",
    features: [
      "Exhibition Stand Design & Build",
      "Pop-Up Displays & Banner Walls",
      "Event Branding & Identity",
      "Conference Materials",
      "Registration Counters & Info Desks",
      "Stage Backdrops & Set Design",
      "Bunting & Decorative Printing",
      "Event Collateral (lanyards, badges, programs)",
    ],
    products: [
      {
        id: "exhibition-stands",
        slug: "exhibition-stands",
        name: "Exhibition Stands",
        description: "Modular and custom exhibition stands. From 3×3m shell-scheme upgrades to 100+ sqm island stands.",
        image: "/images/products/exhibition-stand.jpg",
        startingPrice: 850000,
        minQty: 1,
        leadTime: "Project-based (2–6 weeks)",
        sizes: ["3×3m shell scheme", "6×3m corner", "Custom island", "Custom sizes"],
        materials: ["Modular aluminum extrusion", "Custom wood & steel", "Tension fabric", "Modular panels"],
        features: ["Design + 3D render", "Fabrication", "On-site installation", "Storage for re-use", "Full graphics"],
        category: "Exhibition & Events",
      },
      {
        id: "popup-displays",
        slug: "popup-displays",
        name: "Pop-Up Displays",
        description: "Pop-up backwalls, banner stands, table throws and portable display kits for trade shows and roadshows.",
        image: "/images/products/popup.jpg",
        startingPrice: 145000,
        minQty: 1,
        leadTime: "3–5 business days",
        sizes: ["1×2m (tabletop)", "2×2.3m (backwall)", "3×2.3m (wide)", "Curved 4×2.3m"],
        materials: ["Aluminum frame", "Tension fabric graphics", "Magnetic panels"],
        features: ["Tool-free setup (under 10 min)", "Carrying case", "LED lighting add-on", "Modular accessories"],
        category: "Exhibition & Events",
      },
      {
        id: "registration-counters",
        slug: "registration-counters",
        name: "Registration Counters",
        description: "Portable registration desks, info counters and bar counters for events, conferences and trade shows.",
        image: "/images/products/counter.jpg",
        startingPrice: 165000,
        minQty: 1,
        leadTime: "5–7 business days",
        sizes: ["Straight counter 1m", "Curved counter", "Custom"],
        materials: ["Aluminum + MDF", "Tension fabric wrap", "Acrylic top option"],
        features: ["Tool-free assembly", "Internal shelving", "Custom graphics", "Lockable storage"],
        category: "Exhibition & Events",
      },
      {
        id: "event-materials",
        slug: "event-materials",
        name: "Conference & Event Materials",
        description: "Badges, lanyards, programs, delegate bags, branded notebooks, pens and welcome kits.",
        image: "/images/products/event-materials.jpg",
        startingPrice: 4500,
        minQty: 50,
        leadTime: "7–14 business days",
        sizes: ["Standard event sizes"],
        materials: ["Paper, plastic, fabric, vinyl"],
        features: ["Variable data (names, QR codes)", "Lanyards in any color", "Custom delegate bags", "Bulk packaging"],
        category: "Exhibition & Events",
      },
    ],
    faqs: [
      {
        q: "Do you design custom exhibition stands?",
        a: "Yes — we have an in-house 3D design team that produces photorealistic renders and full CAD drawings for client approval before fabrication.",
      },
      {
        q: "Can you handle installation at events outside Dar es Salaam?",
        a: "Absolutely. We have installation teams that travel to Zanzibar, Arusha, Dodoma, Mwanza and other cities for trade shows and conferences.",
      },
      {
        q: "Do you rent or sell exhibition stands?",
        a: "Both. Modular pop-up displays are often rented for short events. Custom stands are sold and can be stored for re-use at our facility.",
      },
    ],
    color: "from-indigo-500/20 to-blue-600/10",
  },
  {
    id: "design-studio",
    slug: "design-studio",
    title: "Design Studio",
    image: "/images/service-design-studio.jpg",
    shortDescription:
      "Logo design, packaging design, marketing materials, brand identity and presentation design — by senior designers.",
    description:
      "Packard's in-house design studio. From single logo design to full corporate identity systems, packaging design, marketing collateral, presentation design, illustration and motion graphics. Senior designers with 10+ years experience.",
    hero: "Design that earns attention.",
    icon: "M9.53 16.122a3 3 0 00-5.78 1.128 2.25 2.25 0 01-2.4 2.245 4.5 4.5 0 008.4-2.245c0-.399-.078-.78-.22-1.128zm0 0a15.998 15.998 0 003.388-1.62m-5.043-.025a15.994 15.994 0 011.622-3.395m3.42 3.42a15.995 15.995 0 004.764-4.648l3.876-5.814a1.151 1.151 0 00-1.597-1.597L14.146 6.32a15.996 15.996 0 00-4.649 4.763m3.42 3.42a6.776 6.776 0 00-3.42-3.42",
    features: [
      "Logo Design & Brand Marks",
      "Packaging Design & Dieline",
      "Marketing Materials (Brochures, Flyers, Banners)",
      "Brand Identity Systems",
      "Presentation Design (Pitch Decks, Sales Decks)",
      "Social Media Design Templates",
      "Infographic Design",
      "Illustration & Icon Design",
      "Motion Graphics & Animation",
      "Print Production Management",
    ],
    products: [
      {
        id: "logo-design",
        slug: "logo-design",
        name: "Logo Design",
        description: "Professional logo design with 3 concepts, unlimited revisions until perfect, and full file deliverables.",
        image: "/images/products/logo-design.jpg",
        startingPrice: 250000,
        minQty: 1,
        leadTime: "5–10 business days",
        sizes: ["Vector (any size)"],
        materials: ["AI, EPS, SVG, PDF, PNG (transparent)", "Favicon set", "Black, white, color variants"],
        features: ["3 initial concepts", "Unlimited revisions", "Trademark-ready files", "Brand guidelines mini-doc"],
        category: "Design Studio",
      },
      {
        id: "brand-identity",
        slug: "brand-identity",
        name: "Brand Identity System",
        description: "Complete brand identity — logo + typography + color + photography style + brand guidelines.",
        image: "/images/products/brand-identity.jpg",
        startingPrice: 950000,
        minQty: 1,
        leadTime: "14–28 business days",
        sizes: ["All digital + print formats"],
        materials: ["Logo files (vector)", "Brand guidelines PDF (20+ pages)", "Typography kit", "Color palette", "Template library"],
        features: ["Logo design", "Brand strategy", "Color & typography", "Photography direction", "Brand book", "Asset library"],
        category: "Design Studio",
      },
      {
        id: "packaging-design",
        slug: "packaging-design",
        name: "Packaging Design",
        description: "Custom packaging design from dieline to print-ready artwork. 3D mockups included.",
        image: "/images/products/packaging-design.jpg",
        startingPrice: 450000,
        minQty: 1,
        leadTime: "10–21 business days",
        sizes: ["Any packaging format"],
        materials: ["Print-ready AI/PDF", "Dieline", "3D mockups", "Production-ready files"],
        features: ["Dieline creation", "Print-ready files", "3D mockups", "Material recommendation", "Printer liaison"],
        category: "Design Studio",
      },
      {
        id: "presentation-design",
        slug: "presentation-design",
        name: "Presentation Design",
        description: "Premium pitch decks, sales presentations and keynote slides designed to close deals.",
        image: "/images/products/presentation.jpg",
        startingPrice: 180000,
        minQty: 1,
        leadTime: "5–10 business days",
        sizes: ["16:9 widescreen", "4:3 standard", "Custom"],
        materials: ["PowerPoint (.pptx)", "Google Slides", "Keynote", "PDF"],
        features: ["Up to 30 slides", "Custom illustrations", "Data visualization", "Branded template", "Source files included"],
        category: "Design Studio",
      },
    ],
    faqs: [
      {
        q: "How many logo concepts do I get?",
        a: "Every logo project starts with 3 distinct concepts based on your brief. From there we refine your chosen concept with unlimited revisions until you're delighted.",
      },
      {
        q: "Do I own the copyright of the design?",
        a: "Yes. Once final payment is made, you receive full commercial copyright and ownership of the design. We retain the right to showcase the work in our portfolio.",
      },
      {
        q: "Can you design in Swahili?",
        a: "Yes — we work fluently in both English and Swahili. Bilingual design (e.g., product packaging with both languages) is one of our specialties.",
      },
    ],
    color: "from-fuchsia-500/20 to-pink-600/10",
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getProductBySlug(slug: string): { service: Service; product: typeof services[0]["products"][0] } | undefined {
  for (const s of services) {
    const p = s.products.find((p) => p.slug === slug);
    if (p) return { service: s, product: p };
  }
  return undefined;
}
